# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AffixTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AffixTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x41\x66\x66ixTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xa1\x02\n\x0e\x41\x66\x66ixTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04Name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\x1e\n\x0b\x44\x65scription\x18K \x01(\x0b\x32\t.mlstring\x12\x0f\n\x06Remark\x18\xef\n \x01(\t\x12\r\n\x04Icon\x18\x81\t \x01(\t\x12\x13\n\nEffectType\x18\x8f\x04 \x01(\x05\x12\x13\n\nTargetType\x18\xe0\x05 \x01(\x05\x12\x0e\n\x05Level\x18\xe0\x08 \x01(\x05\x12\x1a\n\x05Mutex\x18\x9c\x07 \x01(\x0b\x32\n.int_array\x12\x1b\n\x06\x45\x66\x66\x65\x63t\x18\xda\x04 \x01(\x0b\x32\n.int_table\x12\"\n\nEffectTime\x18\x80\r \x01(\x0b\x32\r.number_table\x12\x11\n\x08GsChange\x18\x96\x0c \x01(\x05\"\x86\x01\n\rAffixTableMgr\x12/\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32 .bokura.AffixTableMgr.DatasEntry\x1a\x44\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.bokura.AffixTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AffixTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AFFIXTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_AFFIXTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_AFFIXTABLEBASE']._serialized_start=48
  _globals['_AFFIXTABLEBASE']._serialized_end=337
  _globals['_AFFIXTABLEMGR']._serialized_start=340
  _globals['_AFFIXTABLEMGR']._serialized_end=474
  _globals['_AFFIXTABLEMGR_DATASENTRY']._serialized_start=406
  _globals['_AFFIXTABLEMGR_DATASENTRY']._serialized_end=474
# @@protoc_insertion_point(module_scope)
