# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BasicAttrEffectTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BasicAttrEffectTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42\x61sicAttrEffectTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xeb\x03\n\x18\x42\x61sicAttrEffectTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12)\n\x11\x41ttrStrengthTable\x18\x90\x08 \x01(\x0b\x32\r.number_table\x12\x18\n\x0f\x41ttrStrengthMax\x18\xde\x0b \x01(\x05\x12)\n\x11\x41ttrVitalityTable\x18\xcf\x06 \x01(\x0b\x32\r.number_table\x12\x18\n\x0f\x41ttrVitalityMax\x18\x96\x03 \x01(\x05\x12*\n\x12\x41ttrDexterityTable\x18\xcc\x08 \x01(\x0b\x32\r.number_table\x12\x19\n\x10\x41ttrDexterityMax\x18\xc5\x0f \x01(\x05\x12-\n\x15\x41ttrIntelligenceTable\x18\xb0\x07 \x01(\x0b\x32\r.number_table\x12\x1c\n\x13\x41ttrIntelligenceMax\x18\xe5\x0f \x01(\x05\x12%\n\rAttrMindTable\x18\xfd\x04 \x01(\x0b\x32\r.number_table\x12\x14\n\x0b\x41ttrMindMax\x18\xb3\x0f \x01(\x05\x12(\n\x10\x41ttrObserveTable\x18\x81\x03 \x01(\x0b\x32\r.number_table\x12\x17\n\x0e\x41ttrObserveMax\x18\x9a\r \x01(\x05\x12$\n\x10\x41ttrIntroduction\x18\x89\x0b \x01(\x0b\x32\t.mlstring\"\xa4\x01\n\x17\x42\x61sicAttrEffectTableMgr\x12\x39\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32*.bokura.BasicAttrEffectTableMgr.DatasEntry\x1aN\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .bokura.BasicAttrEffectTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BasicAttrEffectTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BASICATTREFFECTTABLEBASE']._serialized_start=58
  _globals['_BASICATTREFFECTTABLEBASE']._serialized_end=549
  _globals['_BASICATTREFFECTTABLEMGR']._serialized_start=552
  _globals['_BASICATTREFFECTTABLEMGR']._serialized_end=716
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._serialized_start=638
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._serialized_end=716
# @@protoc_insertion_point(module_scope)
