# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BuffDataTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BuffDataTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42uffDataTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb5\x01\n\x11\x42uffDataTableBase\x12\x0f\n\x06\x42uffId\x18\xa2\x05 \x01(\x03\x12\"\n\x0b\x41\x63tionArray\x18\xbe\x0b \x01(\x0b\x32\x0c.int64_array\x12\"\n\x0b\x45\x66\x66\x65\x63tArray\x18\x89\x01 \x01(\x0b\x32\x0c.int64_array\x12$\n\rMaterialArray\x18\x9a\x0f \x01(\x0b\x32\x0c.int64_array\x12!\n\nWWiseArray\x18\x99\x0f \x01(\x0b\x32\x0c.int64_array\"\x8f\x01\n\x10\x42uffDataTableMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.BuffDataTableMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.BuffDataTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BuffDataTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUFFDATATABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BUFFDATATABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BUFFDATATABLEBASE']._serialized_start=51
  _globals['_BUFFDATATABLEBASE']._serialized_end=232
  _globals['_BUFFDATATABLEMGR']._serialized_start=235
  _globals['_BUFFDATATABLEMGR']._serialized_end=378
  _globals['_BUFFDATATABLEMGR_DATASENTRY']._serialized_start=307
  _globals['_BUFFDATATABLEMGR_DATASENTRY']._serialized_end=378
# @@protoc_insertion_point(module_scope)
