# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BulletRunTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BulletRunTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42ulletRunTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb1\x05\n\x12\x42ulletRunTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x03\x12\x13\n\nMotionType\x18\xc4\x0f \x01(\x05\x12\x13\n\nStartSpeed\x18\xdb\x03 \x01(\x02\x12\x19\n\x10\x41\x63\x63\x65leratedSpeed\x18\xcf\x0e \x01(\x02\x12\x11\n\x08MaxSpeed\x18\xb2\x06 \x01(\x02\x12\x16\n\rDirectionType\x18\xbc\x07 \x01(\x05\x12\x17\n\x0eIsFollowTarget\x18\x99\r \x01(\x08\x12\x17\n\x0eMaxFollowAngle\x18\xdd\x01 \x01(\x02\x12\x15\n\x0c\x45xStartSpeed\x18\xde\n \x01(\x02\x12\x1b\n\x12\x45xAcceleratedSpeed\x18\xae\x05 \x01(\x02\x12\x13\n\nExMaxSpeed\x18\xf1\x04 \x01(\x02\x12\x11\n\tCurvePath\x18# \x01(\t\x12\x10\n\x07\x43urveId\x18\xaf\x03 \x01(\x03\x12\x17\n\x0eIsRandomRadian\x18\xba\x02 \x01(\x08\x12\x15\n\x0cRandomPosTop\x18\xb9\x03 \x01(\x02\x12\x18\n\x0fRandomPosBottom\x18\xa1\x03 \x01(\x02\x12\x16\n\rRandomPosLeft\x18\x83\x0f \x01(\x02\x12\x17\n\x0eRandomPosRight\x18\xcf\x03 \x01(\x02\x12\x13\n\nFollowType\x18\xa0\t \x01(\x05\x12\x1c\n\tOffsetPos\x18\xa1\x0c \x01(\x0b\x32\x08.vector3\x12\x14\n\x0bOriginalDir\x18\xc4\x07 \x01(\x02\x12\x10\n\x07MinZoom\x18\xb9\t \x01(\x02\x12\x10\n\x07MaxZoom\x18\x83\x0b \x01(\x02\x12\x12\n\tZoomSpeed\x18\xc7\x04 \x01(\x02\x12\x13\n\nZoomIsLoop\x18\xc0\x06 \x01(\x08\x12\x17\n\x0e\x46ollowConfigId\x18\xac\x05 \x01(\x05\x12\x16\n\rCheckObstacle\x18\xa6\x07 \x01(\x08\x12\x10\n\x07IsStand\x18\xef\n \x01(\x08\x12\x15\n\x0cIsLockTarget\x18\xa4\x06 \x01(\x08\x12\x13\n\nIsCanDodge\x18\x8a\x03 \x01(\x08\"\x92\x01\n\x11\x42ulletRunTableMgr\x12\x33\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32$.bokura.BulletRunTableMgr.DatasEntry\x1aH\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.bokura.BulletRunTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BulletRunTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BULLETRUNTABLEBASE']._serialized_start=52
  _globals['_BULLETRUNTABLEBASE']._serialized_end=741
  _globals['_BULLETRUNTABLEMGR']._serialized_start=744
  _globals['_BULLETRUNTABLEMGR']._serialized_end=890
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._serialized_start=818
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._serialized_end=890
# @@protoc_insertion_point(module_scope)
