# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BulletTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BulletTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42ulletTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xd9\x02\n\x0f\x42ulletTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12\x0e\n\x05Start\x18\xa6\x05 \x01(\x02\x12\x11\n\x08\x44uration\x18\xa0\x04 \x01(\x02\x12\x10\n\x07ModelID\x18\xdb\x0f \x01(\x05\x12\x12\n\tBoomCount\x18\xd4\t \x01(\x05\x12\x15\n\x0c\x42oomInterval\x18\xda\r \x01(\x05\x12\x17\n\x0e\x44\x61mageInterval\x18\xe0\r \x01(\x05\x12\x15\n\x0c\x42ulletAttrId\x18\xfa\r \x01(\x03\x12\x19\n\x04Tags\x18\xe8\x01 \x01(\x0b\x32\n.int_array\x12\x18\n\x0f\x44\x65\x61\x64ShowStageId\x18\xfc\x0f \x01(\x05\x12\x14\n\x0b\x42ulletCount\x18\xa3\n \x01(\x05\x12\x1f\n\x0c\x44\x61mageWeight\x18\xcf\x0c \x01(\x0b\x32\x08.vector2\x12\x19\n\x10\x44\x61mageWeightType\x18\xc6\n \x01(\x05\x12\x13\n\nFakeBullet\x18\x9e\x0c \x01(\x08\"\x89\x01\n\x0e\x42ulletTableMgr\x12\x30\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32!.bokura.BulletTableMgr.DatasEntry\x1a\x45\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.bokura.BulletTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BulletTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BULLETTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BULLETTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BULLETTABLEBASE']._serialized_start=49
  _globals['_BULLETTABLEBASE']._serialized_end=394
  _globals['_BULLETTABLEMGR']._serialized_start=397
  _globals['_BULLETTABLEMGR']._serialized_end=534
  _globals['_BULLETTABLEMGR_DATASENTRY']._serialized_start=465
  _globals['_BULLETTABLEMGR_DATASENTRY']._serialized_end=534
# @@protoc_insertion_point(module_scope)
