# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CameraShowDataTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CameraShowDataTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x43\x61meraShowDataTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x86\x04\n\x17\x43\x61meraShowDataTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x03\x12\x0e\n\x05Start\x18\xa6\x05 \x01(\x02\x12\x11\n\x08\x44uration\x18\xa0\x04 \x01(\x02\x12\x0c\n\x03\x45nd\x18\x87\x0b \x01(\x02\x12\x13\n\nIsAttacker\x18\x98\x07 \x01(\x08\x12\x10\n\x07StateId\x18\xb4\x02 \x01(\x05\x12\x10\n\x07GroupId\x18\xc4\x01 \x01(\x05\x12\x19\n\x10\x43\x61meraEffectType\x18\xb6\x04 \x01(\x05\x12\x12\n\tFrequency\x18\xfc\x06 \x01(\x02\x12\x1c\n\tAmplitude\x18\xf4\x01 \x01(\x0b\x32\x08.vector3\x12&\n\x0e\x46requencyCurve\x18\x9e\x01 \x01(\x0b\x32\r.number_table\x12&\n\x0e\x41mplitudeCurve\x18\xe8\x0f \x01(\x0b\x32\r.number_table\x12\x13\n\nOnlyCaster\x18\xec\x03 \x01(\x08\x12\x14\n\x0bMaxDistance\x18\xda\x03 \x01(\x02\x12%\n\rDistanceCurve\x18\xd2\x0e \x01(\x0b\x32\r.number_table\x12\x12\n\tIntensity\x18\xf1\x06 \x01(\x02\x12&\n\x0eIntensityCurve\x18\x99\x01 \x01(\x0b\x32\r.number_table\x12\x12\n\tThreshold\x18\xaa\x06 \x01(\x02\x12\x11\n\x08IsRandom\x18\xa5\x0c \x01(\x08\x12\"\n\nExtraParms\x18\xca\x01 \x01(\x0b\x32\r.number_array\"\xa1\x01\n\x16\x43\x61meraShowDataTableMgr\x12\x38\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32).bokura.CameraShowDataTableMgr.DatasEntry\x1aM\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.bokura.CameraShowDataTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CameraShowDataTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERASHOWDATATABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_CAMERASHOWDATATABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_CAMERASHOWDATATABLEBASE']._serialized_start=57
  _globals['_CAMERASHOWDATATABLEBASE']._serialized_end=575
  _globals['_CAMERASHOWDATATABLEMGR']._serialized_start=578
  _globals['_CAMERASHOWDATATABLEMGR']._serialized_end=739
  _globals['_CAMERASHOWDATATABLEMGR_DATASENTRY']._serialized_start=662
  _globals['_CAMERASHOWDATATABLEMGR_DATASENTRY']._serialized_end=739
# @@protoc_insertion_point(module_scope)
