# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChallengeHeroDungeonTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ChallengeHeroDungeonTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43hallengeHeroDungeonTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x94\x03\n\x1d\x43hallengeHeroDungeonTableBase\x12\x12\n\tDungeonId\x18\xaf\x0c \x01(\x05\x12\x15\n\x0c\x44ungeonGroup\x18\xd9\x03 \x01(\x05\x12\x12\n\tStarLevel\x18\xf0\t \x01(\x05\x12\x11\n\x08LabelPic\x18\xe9\x0b \x01(\t\x12\x13\n\nBackground\x18\xd7\x02 \x01(\t\x12\x10\n\x07ModelId\x18\xab\x04 \x01(\x05\x12\x11\n\x08\x45\x66\x66\x65\x63tId\x18\x93\x0c \x01(\t\x12 \n\x0b\x45xtraTarget\x18\xb1\n \x01(\x0b\x32\n.int_array\x12\x12\n\tBaseRatio\x18\xfc\x08 \x01(\x05\x12\x1a\n\x05\x41\x66\x66ix\x18\x9c\x0b \x01(\x0b\x32\n.int_table\x12 \n\x0bSelectAffix\x18\xdb\t \x01(\x0b\x32\n.int_table\x12\x1e\n\tScoreRank\x18\xe5\x05 \x01(\x0b\x32\n.int_table\x12\x12\n\tLimitTime\x18\xdc\x02 \x01(\x05\x12\x1f\n\nScoreAward\x18\x92\x08 \x01(\x0b\x32\n.int_table\x12\x1e\n\tKeyReward\x18\xff\r \x01(\x0b\x32\n.int_array\"\xb3\x01\n\x1c\x43hallengeHeroDungeonTableMgr\x12>\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32/.bokura.ChallengeHeroDungeonTableMgr.DatasEntry\x1aS\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.bokura.ChallengeHeroDungeonTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeHeroDungeonTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHALLENGEHERODUNGEONTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_CHALLENGEHERODUNGEONTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_CHALLENGEHERODUNGEONTABLEBASE']._serialized_start=63
  _globals['_CHALLENGEHERODUNGEONTABLEBASE']._serialized_end=467
  _globals['_CHALLENGEHERODUNGEONTABLEMGR']._serialized_start=470
  _globals['_CHALLENGEHERODUNGEONTABLEMGR']._serialized_end=649
  _globals['_CHALLENGEHERODUNGEONTABLEMGR_DATASENTRY']._serialized_start=566
  _globals['_CHALLENGEHERODUNGEONTABLEMGR_DATASENTRY']._serialized_end=649
# @@protoc_insertion_point(module_scope)
