# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChangeQueueTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ChangeQueueTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43hangeQueueTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe5\x01\n\x14\x43hangeQueueTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\r\n\x04Sort\x18\xeb\x0c \x01(\x05\x12\x1f\n\nConsumable\x18\xaa\x03 \x01(\x0b\x32\n.int_table\x12\x17\n\x0e\x43onsumableName\x18\x95\r \x01(\t\x12\"\n\rExchangeGoods\x18\xcd\x08 \x01(\x0b\x32\n.int_table\x12\x15\n\x0c\x45xchangeName\x18\xbe\x0b \x01(\t\x12\x1e\n\tCondition\x18\xe2\x0c \x01(\x0b\x32\n.int_table\x12\x1c\n\x08WaitTime\x18j \x01(\x0b\x32\n.int_array\"\x98\x01\n\x13\x43hangeQueueTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.ChangeQueueTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.ChangeQueueTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChangeQueueTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGEQUEUETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_CHANGEQUEUETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_CHANGEQUEUETABLEBASE']._serialized_start=54
  _globals['_CHANGEQUEUETABLEBASE']._serialized_end=283
  _globals['_CHANGEQUEUETABLEMGR']._serialized_start=286
  _globals['_CHANGEQUEUETABLEMGR']._serialized_end=438
  _globals['_CHANGEQUEUETABLEMGR_DATASENTRY']._serialized_start=364
  _globals['_CHANGEQUEUETABLEMGR_DATASENTRY']._serialized_end=438
# @@protoc_insertion_point(module_scope)
