# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ComposeTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ComposeTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43omposeTable.proto\x12\x06\x62okura\"\xc5\x01\n\x10\x43omposeTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x11\n\x08SystemId\x18\x86\x04 \x01(\x05\x12\r\n\x04Nums\x18\x8a\x0c \x01(\x05\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12\x1e\n\x15SuccessfulProbability\x18\xcc\t \x01(\x05\x12\x11\n\x08ObtainID\x18\xaf\x08 \x01(\x05\x12\x12\n\tObtainNum\x18\x89\x0f \x01(\x05\x12\x13\n\nObtainName\x18\xdb\x0c \x01(\t\x12\x17\n\x0e\x43onsumableTips\x18\x85\x07 \x01(\x05\"\x8c\x01\n\x0f\x43omposeTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.ComposeTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.ComposeTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ComposeTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPOSETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_COMPOSETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_COMPOSETABLEBASE']._serialized_start=31
  _globals['_COMPOSETABLEBASE']._serialized_end=228
  _globals['_COMPOSETABLEMGR']._serialized_start=231
  _globals['_COMPOSETABLEMGR']._serialized_end=371
  _globals['_COMPOSETABLEMGR_DATASENTRY']._serialized_start=301
  _globals['_COMPOSETABLEMGR_DATASENTRY']._serialized_end=371
# @@protoc_insertion_point(module_scope)
