# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CutsceneTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CutsceneTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43utsceneTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xde\x04\n\x11\x43utsceneTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x13\n\nNameDesign\x18\xf1\x0c \x01(\t\x12\x10\n\x07ResPath\x18\xa4\x04 \x01(\t\x12\x16\n\rContentHiding\x18\x82\t \x01(\x05\x12\x19\n\x10IsCutsceneEditor\x18\xf7\x01 \x01(\x08\x12\x10\n\x07\x43\x61nSkip\x18\xbb\x02 \x01(\x05\x12\x15\n\x0cValidateSkip\x18\xb4\t \x01(\x08\x12\x1e\n\tBlackMask\x18\x8f\x07 \x01(\x0b\x32\n.int_array\x12\x1f\n\nAllowInput\x18\x80\x02 \x01(\x0b\x32\n.int_array\x12\x18\n\x0fIsSavePlayState\x18\x85\x0c \x01(\x08\x12\x1a\n\x11\x43heckPlayKeyIndex\x18\xb5\x04 \x01(\x05\x12%\n\x10\x45ndSyncActorType\x18\xda\t \x01(\x0b\x32\n.int_array\x12#\n\x0e\x45ndSyncActorId\x18\xe7\x0f \x01(\x0b\x32\n.int_array\x12(\n\x0f\x45ndSyncActorPos\x18\xc8\x0b \x01(\x0b\x32\x0e.vector3_array\x12,\n\x14\x45ndSyncActorRotation\x18\xf2\r \x01(\x0b\x32\r.number_array\x12\x16\n\rCheckPlayType\x18\xfe\x0e \x01(\x05\x12\x13\n\nAudioState\x18\xef\x05 \x01(\t\x12\x15\n\x0c\x42indingScene\x18\xcf\t \x01(\x05\x12\x16\n\x0ePlayerSyncType\x18\x14 \x01(\x05\x12%\n\rPlayerSyncPos\x18\xe1\x06 \x01(\x0b\x32\r.number_array\x12\x1b\n\x12PlayerSyncRotation\x18\xbc\x04 \x01(\x02\"\x8f\x01\n\x10\x43utsceneTableMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.CutsceneTableMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.CutsceneTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CutsceneTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUTSCENETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_CUTSCENETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_CUTSCENETABLEBASE']._serialized_start=51
  _globals['_CUTSCENETABLEBASE']._serialized_end=657
  _globals['_CUTSCENETABLEMGR']._serialized_start=660
  _globals['_CUTSCENETABLEMGR']._serialized_end=803
  _globals['_CUTSCENETABLEMGR_DATASENTRY']._serialized_start=732
  _globals['_CUTSCENETABLEMGR_DATASENTRY']._serialized_end=803
# @@protoc_insertion_point(module_scope)
