# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DummyTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DummyTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x44ummyTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb7\x02\n\x0e\x44ummyTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12\x10\n\x07SkillId\x18\xbf\x08 \x01(\x05\x12\x12\n\tWalkSpeed\x18\xd9\x04 \x01(\x02\x12\x10\n\x08RunSpeed\x18R \x01(\x02\x12\x1d\n\x08SkillIds\x18\xd8\x0b \x01(\x0b\x32\n.int_array\x12\x19\n\x10\x41ITableReference\x18\xe3\x07 \x01(\x05\x12\x15\n\x0cIsInitiative\x18\xeb\x01 \x01(\x08\x12\x11\n\x08IsFlying\x18\xd5\x0e \x01(\x08\x12\x14\n\x0b\x42irthEffect\x18\xf0\t \x01(\t\x12\x13\n\nDeadEffect\x18\xda\x02 \x01(\t\x12\x13\n\nBirthAudio\x18\xd2\x04 \x01(\t\x12\x12\n\tDeadAudio\x18\x97\x04 \x01(\t\x12\x19\n\x04Tags\x18\xe8\x01 \x01(\x0b\x32\n.int_array\"\x86\x01\n\rDummyTableMgr\x12/\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32 .bokura.DummyTableMgr.DatasEntry\x1a\x44\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.bokura.DummyTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DummyTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUMMYTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_DUMMYTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_DUMMYTABLEBASE']._serialized_start=48
  _globals['_DUMMYTABLEBASE']._serialized_end=359
  _globals['_DUMMYTABLEMGR']._serialized_start=362
  _globals['_DUMMYTABLEMGR']._serialized_end=496
  _globals['_DUMMYTABLEMGR_DATASENTRY']._serialized_start=428
  _globals['_DUMMYTABLEMGR_DATASENTRY']._serialized_end=496
# @@protoc_insertion_point(module_scope)
