# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EventShowDataTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EventShowDataTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x45ventShowDataTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xc6\x01\n\x16\x45ventShowDataTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x03\x12\x0e\n\x05Start\x18\xa6\x05 \x01(\x02\x12\x11\n\x08\x44uration\x18\xa0\x04 \x01(\x02\x12\x0c\n\x03\x45nd\x18\x87\x0b \x01(\x02\x12\x13\n\nIsAttacker\x18\x98\x07 \x01(\x08\x12\x10\n\x07StateId\x18\xb4\x02 \x01(\x05\x12\x10\n\x07GroupId\x18\xc4\x01 \x01(\x05\x12\x12\n\tEventType\x18\xcb\n \x01(\x05\x12!\n\tParamList\x18\x9e\n \x01(\x0b\x32\r.string_table\"\x9e\x01\n\x15\x45ventShowDataTableMgr\x12\x37\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32(.bokura.EventShowDataTableMgr.DatasEntry\x1aL\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.bokura.EventShowDataTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EventShowDataTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSHOWDATATABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_EVENTSHOWDATATABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_EVENTSHOWDATATABLEBASE']._serialized_start=56
  _globals['_EVENTSHOWDATATABLEBASE']._serialized_end=254
  _globals['_EVENTSHOWDATATABLEMGR']._serialized_start=257
  _globals['_EVENTSHOWDATATABLEMGR']._serialized_end=415
  _globals['_EVENTSHOWDATATABLEMGR_DATASENTRY']._serialized_start=339
  _globals['_EVENTSHOWDATATABLEMGR_DATASENTRY']._serialized_end=415
# @@protoc_insertion_point(module_scope)
