# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ExchangeItemTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ExchangeItemTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x45xchangeItemTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf8\x01\n\x15\x45xchangeItemTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x13\n\nExchangeID\x18\xc2\x01 \x01(\x05\x12\x12\n\tGetItemId\x18\xdb\x07 \x01(\x05\x12\x0f\n\x06GetNum\x18\x99\x02 \x01(\x05\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12!\n\x0c\x43onsumableID\x18\x98\x07 \x01(\x0b\x32\n.int_table\x12\x19\n\x10UnlockConditions\x18\xe5\x04 \x01(\t\x12\x14\n\x0bRefreshType\x18\xd5\x01 \x01(\x05\x12\x13\n\nRefreshNum\x18\xe0\n \x01(\x05\x12\x11\n\x08SexLimit\x18\x9a\x06 \x01(\x05\x12\r\n\x04Sort\x18\xeb\x0c \x01(\x05\"\x9b\x01\n\x14\x45xchangeItemTableMgr\x12\x36\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\'.bokura.ExchangeItemTableMgr.DatasEntry\x1aK\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.bokura.ExchangeItemTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExchangeItemTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGEITEMTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_EXCHANGEITEMTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_EXCHANGEITEMTABLEBASE']._serialized_start=55
  _globals['_EXCHANGEITEMTABLEBASE']._serialized_end=303
  _globals['_EXCHANGEITEMTABLEMGR']._serialized_start=306
  _globals['_EXCHANGEITEMTABLEMGR']._serialized_end=461
  _globals['_EXCHANGEITEMTABLEMGR_DATASENTRY']._serialized_start=386
  _globals['_EXCHANGEITEMTABLEMGR_DATASENTRY']._serialized_end=461
# @@protoc_insertion_point(module_scope)
