# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ExchangeTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ExchangeTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x45xchangeTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x8c\x01\n\x11\x45xchangeTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x1c\n\x08ShopName\x18\xe3\n \x01(\x0b\x32\t.mlstring\x12\x11\n\x08SystemId\x18\x86\x04 \x01(\x05\x12\x0c\n\x03Npc\x18\xd6\x06 \x01(\t\x12\x11\n\x08ShowType\x18\xeb\x08 \x01(\x05\x12\x18\n\x0f\x43urrencyDisplay\x18\xfe\x07 \x01(\t\"\x8f\x01\n\x10\x45xchangeTableMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.ExchangeTableMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.ExchangeTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExchangeTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_EXCHANGETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_EXCHANGETABLEBASE']._serialized_start=51
  _globals['_EXCHANGETABLEBASE']._serialized_end=191
  _globals['_EXCHANGETABLEMGR']._serialized_start=194
  _globals['_EXCHANGETABLEMGR']._serialized_end=337
  _globals['_EXCHANGETABLEMGR_DATASENTRY']._serialized_start=266
  _globals['_EXCHANGETABLEMGR_DATASENTRY']._serialized_end=337
# @@protoc_insertion_point(module_scope)
