# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FaceStickerTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FaceStickerTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x46\x61\x63\x65StickerTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf4\x01\n\x14\x46\x61\x63\x65StickerTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12!\n\x0c\x44\x65\x66\x61ultColor\x18\x8b\x0f \x01(\x0b\x32\n.int_array\x12\x10\n\x07\x43olorId\x18\xf1\x08 \x01(\x05\x12\r\n\x04\x42\x61\x63k\x18\xfb\x01 \x01(\x05\x12\r\n\x04Move\x18\x95\t \x01(\x05\x12\x0f\n\x06Rotate\x18\x8d\x0b \x01(\x05\x12\x0e\n\x05Scale\x18\x85\x0f \x01(\x05\x12\x1f\n\x0c\x44\x65\x66\x61ultScale\x18\x99\x04 \x01(\x0b\x32\x08.vector3\x12\"\n\x0f\x44\x65\x66\x61ultPosition\x18\xab\x0b \x01(\x0b\x32\x08.vector2\x12\x16\n\rDefaultRotate\x18\x86\r \x01(\x02\"\x98\x01\n\x13\x46\x61\x63\x65StickerTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.FaceStickerTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.FaceStickerTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FaceStickerTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACESTICKERTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_FACESTICKERTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_FACESTICKERTABLEBASE']._serialized_start=54
  _globals['_FACESTICKERTABLEBASE']._serialized_end=298
  _globals['_FACESTICKERTABLEMGR']._serialized_start=301
  _globals['_FACESTICKERTABLEMGR']._serialized_end=453
  _globals['_FACESTICKERTABLEMGR_DATASENTRY']._serialized_start=379
  _globals['_FACESTICKERTABLEMGR_DATASENTRY']._serialized_end=453
# @@protoc_insertion_point(module_scope)
