# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FantasyTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FantasyTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46\x61ntasyTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf3\x01\n\x10\x46\x61ntasyTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04Name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\x14\n\x0b\x46\x61ntasyType\x18\xfd\x02 \x01(\x05\x12\x13\n\nFantasyArt\x18\xe4\x06 \x01(\t\x12\x14\n\x0b\x46\x61ntasyTips\x18\xb4\x0c \x01(\t\x12\"\n\rResTemplateId\x18\xf8\n \x01(\x0b\x32\n.int_table\x12$\n\x0c\x42uffValueKey\x18\x9c\x05 \x01(\x0b\x32\r.string_table\x12\x1c\n\x07\x42uffPar\x18\x98\r \x01(\x0b\x32\n.int_table\x12\x0f\n\x06IsOnly\x18\xaf\x01 \x01(\x08\"\x8c\x01\n\x0f\x46\x61ntasyTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.FantasyTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.FantasyTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FantasyTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FANTASYTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_FANTASYTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_FANTASYTABLEBASE']._serialized_start=50
  _globals['_FANTASYTABLEBASE']._serialized_end=293
  _globals['_FANTASYTABLEMGR']._serialized_start=296
  _globals['_FANTASYTABLEMGR']._serialized_end=436
  _globals['_FANTASYTABLEMGR_DATASENTRY']._serialized_start=366
  _globals['_FANTASYTABLEMGR_DATASENTRY']._serialized_end=436
# @@protoc_insertion_point(module_scope)
