# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FashionTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FashionTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46\x61shionTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe3\x03\n\x10\x46\x61shionTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\r\n\x04Type\x18\xa1\x05 \x01(\x05\x12\x0f\n\x06SortID\x18\xf8\x03 \x01(\x05\x12\x0e\n\x05Model\x18\xa5\x03 \x01(\t\x12\x1e\n\x06Model2\x18\x8f\r \x01(\x0b\x32\r.string_table\x12\x10\n\x07ModelId\x18\xab\x04 \x01(\t\x12\x14\n\x0b\x46\x61shionType\x18\x8d\x03 \x01(\x05\x12\x1d\n\x08HidePart\x18\xd7\x03 \x01(\x0b\x32\n.int_array\x12\x1b\n\x06HairId\x18\x8a\x05 \x01(\x0b\x32\n.int_array\x12!\n\x0c\x44\x65\x66\x61ultColor\x18\x8b\x0f \x01(\x0b\x32\n.int_table\x12\x1e\n\tColorPart\x18\x9b\x04 \x01(\x0b\x32\n.int_array\x12\x15\n\x0c\x43olorGroupId\x18\xc3\x08 \x01(\x05\x12\x0f\n\x06IsHide\x18\xbb\x0e \x01(\x05\x12\x12\n\tArmLength\x18\x97\x0b \x01(\x05\x12\x11\n\x08\x41rmWidth\x18\xef\t \x01(\x05\x12\x14\n\x0bWaistLength\x18\x9d\x0f \x01(\x05\x12\x13\n\nWaistWidth\x18\xc8\x0b \x01(\x05\x12\x12\n\tLegLength\x18\x9a\x04 \x01(\x05\x12\x11\n\x08LegWidth\x18\xc6\x0f \x01(\x05\x12\x13\n\nSwitchName\x18\xe3\x01 \x01(\t\x12\x15\n\x0cHeadwearType\x18\x90\x04 \x01(\x05\"\x8c\x01\n\x0f\x46\x61shionTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.FashionTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.FashionTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FashionTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FASHIONTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_FASHIONTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_FASHIONTABLEBASE']._serialized_start=50
  _globals['_FASHIONTABLEBASE']._serialized_end=533
  _globals['_FASHIONTABLEMGR']._serialized_start=536
  _globals['_FASHIONTABLEMGR']._serialized_end=676
  _globals['_FASHIONTABLEMGR_DATASENTRY']._serialized_start=606
  _globals['_FASHIONTABLEMGR_DATASENTRY']._serialized_end=676
# @@protoc_insertion_point(module_scope)
