# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FightAttrTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FightAttrTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x46ightAttrTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf1\x03\n\x12\x46ightAttrTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x11\n\x08\x45numName\x18\xb9\x08 \x01(\t\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12\r\n\x04Type\x18\xa1\x05 \x01(\t\x12\x10\n\x07IsClass\x18\x9a\x04 \x01(\x08\x12\x11\n\x08IsSyncMe\x18\xa8\x08 \x01(\x08\x12\x11\n\tIsSyncAoi\x18p \x01(\x08\x12\x17\n\x0e\x41ttrLowerLimit\x18\xbc\x0c \x01(\x05\x12\x17\n\x0e\x41ttrUpperLimit\x18\xf6\n \x01(\x03\x12\x0e\n\x05Level\x18\xe0\x08 \x01(\x05\x12\x12\n\tAttrFinal\x18\x83\x06 \x01(\x05\x12\x12\n\tAttrTotal\x18\x99\x06 \x01(\x05\x12\x10\n\x07\x41ttrAdd\x18\xd7\x01 \x01(\x05\x12\x12\n\tAttrExAdd\x18\x96\x0e \x01(\x05\x12\x10\n\x07\x41ttrPer\x18\xdb\r \x01(\x05\x12\x12\n\tAttrExPer\x18\x91\x0f \x01(\x05\x12\x13\n\x0b\x41ttrNumType\x18i \x01(\x05\x12 \n\x0cOfficialName\x18\x9f\x04 \x01(\x0b\x32\t.mlstring\x12\x1f\n\x0bTipTemplate\x18\xe7\r \x01(\x0b\x32\t.mlstring\x12\x1b\n\x07\x41ttrDes\x18\x87\n \x01(\x0b\x32\t.mlstring\x12\x18\n\x0f\x42uffShowAttrHUD\x18\xad\x06 \x01(\x05\x12 \n\x08\x41ttrIcon\x18\x8b\n \x01(\x0b\x32\r.string_array\"\x92\x01\n\x11\x46ightAttrTableMgr\x12\x33\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32$.bokura.FightAttrTableMgr.DatasEntry\x1aH\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.bokura.FightAttrTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FightAttrTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIGHTATTRTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_FIGHTATTRTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_FIGHTATTRTABLEBASE']._serialized_start=52
  _globals['_FIGHTATTRTABLEBASE']._serialized_end=549
  _globals['_FIGHTATTRTABLEMGR']._serialized_start=552
  _globals['_FIGHTATTRTABLEMGR']._serialized_end=698
  _globals['_FIGHTATTRTABLEMGR_DATASENTRY']._serialized_start=626
  _globals['_FIGHTATTRTABLEMGR_DATASENTRY']._serialized_end=698
# @@protoc_insertion_point(module_scope)
