# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HelpLibraryTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HelpLibraryTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16HelpLibraryTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x83\x03\n\x14HelpLibraryTableBase\x12\x0f\n\x06sortId\x18\xb4\x02 \x01(\x05\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\r\n\x04Type\x18\xa1\x05 \x01(\x05\x12\x12\n\tTypeGroup\x18\xf7\x06 \x01(\x05\x12\x1d\n\tMainTitle\x18\x84\x01 \x01(\x0b\x32\t.mlstring\x12\x12\n\tHelpGroup\x18\xac\x04 \x01(\x05\x12\x1d\n\tGroupName\x18\xc5\x04 \x01(\x0b\x32\t.mlstring\x12\x19\n\x05Title\x18\xb7\x05 \x01(\x0b\x32\t.mlstring\x12!\n\x07\x43ontent\x18\x8f\x06 \x01(\x0b\x32\x0f.mlstring_array\x12\x1b\n\x03Res\x18\xfb\t \x01(\x0b\x32\r.string_array\x12\x11\n\x08Sequence\x18\xbf\x06 \x01(\x05\x12\x15\n\x0c\x44urationTime\x18\xc8\x04 \x01(\x05\x12\x12\n\tEventType\x18\xcb\n \x01(\x05\x12\x0e\n\x05Param\x18\xb7\t \x01(\t\x12\x1a\n\x06\x42utton\x18\x87\x0f \x01(\x0b\x32\t.mlstring\x12\x13\n\nFunctionId\x18\x95\x01 \x01(\x05\"\x98\x01\n\x13HelpLibraryTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.HelpLibraryTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.HelpLibraryTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HelpLibraryTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELPLIBRARYTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_HELPLIBRARYTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_HELPLIBRARYTABLEBASE']._serialized_start=54
  _globals['_HELPLIBRARYTABLEBASE']._serialized_end=441
  _globals['_HELPLIBRARYTABLEMGR']._serialized_start=444
  _globals['_HELPLIBRARYTABLEMGR']._serialized_end=596
  _globals['_HELPLIBRARYTABLEMGR_DATASENTRY']._serialized_start=522
  _globals['_HELPLIBRARYTABLEMGR_DATASENTRY']._serialized_end=596
# @@protoc_insertion_point(module_scope)
