# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MallItemTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MallItemTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MallItemTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xd6\x04\n\x11MallItemTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x0f\n\x06ItemId\x18\xf8\x03 \x01(\x05\x12\x11\n\x08Quantity\x18\xe9\x0c \x01(\x05\x12\x11\n\x08ItemName\x18\xc5\x0b \x01(\t\x12\r\n\x04Sort\x18\xeb\x0c \x01(\x05\x12\x13\n\nFunctionId\x18\x95\x01 \x01(\x05\x12\x11\n\x08LimitSex\x18\xc3\x06 \x01(\x05\x12\x13\n\nLimitLevel\x18\xce\x05 \x01(\x05\x12\x12\n\tLimitTime\x18\xdc\x02 \x01(\x05\x12\"\n\rShowLimitType\x18\xb1\x03 \x01(\x0b\x32\n.int_table\x12\"\n\rOriginalPrice\x18\x9d\x0f \x01(\x0b\x32\n.int_array\x12\x32\n\x04\x43ost\x18\xa0\x08 \x03(\x0b\x32#.bokura.MallItemTableBase.CostEntry\x12 \n\x0bRefreshType\x18\xd5\x01 \x01(\x0b\x32\n.int_table\x12\r\n\x04\x42ind\x18\x8b\x0e \x01(\x05\x12\x1f\n\nDeliverWay\x18\xb7\x03 \x01(\x0b\x32\n.int_table\x12\x1d\n\x05Label\x18\xb0\x03 \x01(\x0b\x32\r.string_array\x12%\n\rShowCountDown\x18\xa8\t \x01(\x0b\x32\r.string_array\x12(\n\x13WeightPoolParameter\x18\xcc\x0b \x01(\x0b\x32\n.int_table\x12\x1b\n\x06Weight\x18\x8c\x01 \x01(\x0b\x32\n.int_table\x12\x15\n\x0c\x43heckDisplay\x18\xd5\x02 \x01(\x05\x1a+\n\tCostEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x8f\x01\n\x10MallItemTableMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.MallItemTableMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.MallItemTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MallItemTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MALLITEMTABLEBASE_COSTENTRY']._loaded_options = None
  _globals['_MALLITEMTABLEBASE_COSTENTRY']._serialized_options = b'8\001'
  _globals['_MALLITEMTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MALLITEMTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MALLITEMTABLEBASE']._serialized_start=51
  _globals['_MALLITEMTABLEBASE']._serialized_end=649
  _globals['_MALLITEMTABLEBASE_COSTENTRY']._serialized_start=606
  _globals['_MALLITEMTABLEBASE_COSTENTRY']._serialized_end=649
  _globals['_MALLITEMTABLEMGR']._serialized_start=652
  _globals['_MALLITEMTABLEMGR']._serialized_end=795
  _globals['_MALLITEMTABLEMGR_DATASENTRY']._serialized_start=724
  _globals['_MALLITEMTABLEMGR_DATASENTRY']._serialized_end=795
# @@protoc_insertion_point(module_scope)
