# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ModTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ModTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eModTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xaa\x01\n\x0cModTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x0f\n\x06ModPic\x18\xc5\x01 \x01(\t\x12\x0f\n\x06ModLvl\x18\x8b\x03 \x01(\x05\x12\x13\n\nEffectType\x18\x8f\x04 \x01(\x05\x12\x14\n\x0c\x45\x66\x66\x65\x63tConfig\x18n \x01(\x05\x12$\n\x0f\x45\x66\x66\x65\x63tParameter\x18\xf9\x05 \x01(\x0b\x32\n.int_array\x12\x1a\n\x05TagId\x18\x9e\x08 \x01(\x0b\x32\n.int_array\"\x80\x01\n\x0bModTableMgr\x12-\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x1e.bokura.ModTableMgr.DatasEntry\x1a\x42\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.bokura.ModTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ModTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MODTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MODTABLEBASE']._serialized_start=46
  _globals['_MODTABLEBASE']._serialized_end=216
  _globals['_MODTABLEMGR']._serialized_start=219
  _globals['_MODTABLEMGR']._serialized_end=347
  _globals['_MODTABLEMGR_DATASENTRY']._serialized_start=281
  _globals['_MODTABLEMGR_DATASENTRY']._serialized_end=347
# @@protoc_insertion_point(module_scope)
