# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MonsterFightAreaTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MonsterFightAreaTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bMonsterFightAreaTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xed\x01\n\x19MonsterFightAreaTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12 \n\x08\x41reaName\x18\x80\x0b \x01(\x0b\x32\r.string_array\x12#\n\x0e\x41reaHateWeight\x18\xeb\x05 \x01(\x0b\x32\n.int_array\x12\"\n\nAreaRadius\x18\xf3\x03 \x01(\x0b\x32\r.number_table\x12\x1a\n\x11\x41reaMaximumRadius\x18\x86\x02 \x01(\x02\x12!\n\tAreaAngle\x18\xd9\t \x01(\x0b\x32\r.number_table\x12\x19\n\x10PlayerHateWeight\x18\x9c\t \x01(\x02\"\xa7\x01\n\x18MonsterFightAreaTableMgr\x12:\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32+.bokura.MonsterFightAreaTableMgr.DatasEntry\x1aO\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.bokura.MonsterFightAreaTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MonsterFightAreaTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONSTERFIGHTAREATABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MONSTERFIGHTAREATABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERFIGHTAREATABLEBASE']._serialized_start=59
  _globals['_MONSTERFIGHTAREATABLEBASE']._serialized_end=296
  _globals['_MONSTERFIGHTAREATABLEMGR']._serialized_start=299
  _globals['_MONSTERFIGHTAREATABLEMGR']._serialized_end=466
  _globals['_MONSTERFIGHTAREATABLEMGR_DATASENTRY']._serialized_start=387
  _globals['_MONSTERFIGHTAREATABLEMGR_DATASENTRY']._serialized_end=466
# @@protoc_insertion_point(module_scope)
