# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QuestStepTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'QuestStepTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14QuestStepTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xed\x04\n\x12QuestStepTableBase\x12\x14\n\x0bQuestStepId\x18\xe1\x03 \x01(\x05\x12\x1e\n\tStepParam\x18\xb2\x04 \x01(\x0b\x32\n.int_table\x12\x10\n\x07LuaJump\x18\xb6\x04 \x01(\t\x12\x13\n\nFailToStep\x18\xd8\n \x01(\x05\x12\x17\n\x0e\x43ompleteToStep\x18\xd6\x0e \x01(\x05\x12$\n\x0f\x43ompleteAllStep\x18\xcc\x07 \x01(\x0b\x32\n.int_array\x12\"\n\rNpcTalkChange\x18\xff\x07 \x01(\x0b\x32\n.int_table\x12\x1f\n\nQuestItems\x18\x8b\x0b \x01(\x0b\x32\n.int_table\x12\x1c\n\x08StepTips\x18\xd0\x02 \x01(\x0b\x32\t.mlstring\x12\x17\n\x0eQuestClickJump\x18\x95\x0f \x01(\x05\x12$\n\x0fTimeLimitedStep\x18\xb0\x07 \x01(\x0b\x32\n.int_array\x12\x17\n\x0eStepTargetType\x18\xc3\x0c \x01(\x05\x12+\n\x13StepTargetCondition\x18\x8b\n \x01(\x0b\x32\r.string_table\x12%\n\rStepTargetPos\x18\xbc\n \x01(\x0b\x32\r.string_table\x12!\n\rStepMainTitle\x18\xb0\n \x01(\x0b\x32\t.mlstring\x12(\n\x0eStepTargetInfo\x18\xeb\x03 \x01(\x0b\x32\x0f.mlstring_array\x12\x19\n\x10\x44isableTransport\x18\xf6\x05 \x01(\x05\x12\x13\n\nSceneCheck\x18\xae\x02 \x01(\x05\x12\x18\n\x10VisualLayerCheck\x18T \x01(\x05\x12\x15\n\x0cHideTrackBar\x18\xeb\x01 \x01(\x08\"\x92\x01\n\x11QuestStepTableMgr\x12\x33\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32$.bokura.QuestStepTableMgr.DatasEntry\x1aH\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.bokura.QuestStepTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QuestStepTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTSTEPTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_QUESTSTEPTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_QUESTSTEPTABLEBASE']._serialized_start=52
  _globals['_QUESTSTEPTABLEBASE']._serialized_end=673
  _globals['_QUESTSTEPTABLEMGR']._serialized_start=676
  _globals['_QUESTSTEPTABLEMGR']._serialized_end=822
  _globals['_QUESTSTEPTABLEMGR_DATASENTRY']._serialized_start=750
  _globals['_QUESTSTEPTABLEMGR_DATASENTRY']._serialized_end=822
# @@protoc_insertion_point(module_scope)
