# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QuestTypeTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'QuestTypeTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14QuestTypeTable.proto\x12\x06\x62okura\"\xf5\x01\n\x12QuestTypeTableBase\x12\x14\n\x0bQuestTypeId\x18\xb2\x04 \x01(\x05\x12\x16\n\rQuestTypeName\x18\xd9\x01 \x01(\t\x12\x19\n\x10QuestTypeGroupID\x18\xab\x02 \x01(\x05\x12\x14\n\x0bQuestTypeUI\x18\xbc\x07 \x01(\t\x12\x14\n\x0bShowQuestUI\x18\xe9\x06 \x01(\x08\x12\x12\n\tResetType\x18\xfa\x08 \x01(\x05\x12\x17\n\x0e\x46orcedTracking\x18\xc5\t \x01(\x08\x12\x15\n\x0c\x41utoTracking\x18\xe5\x08 \x01(\x05\x12\x16\n\rQuestListHide\x18\xaa\x0f \x01(\x08\x12\x0e\n\x05order\x18\x90\r \x01(\x05\"\x92\x01\n\x11QuestTypeTableMgr\x12\x33\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32$.bokura.QuestTypeTableMgr.DatasEntry\x1aH\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.bokura.QuestTypeTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QuestTypeTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTTYPETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_QUESTTYPETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_QUESTTYPETABLEBASE']._serialized_start=33
  _globals['_QUESTTYPETABLEBASE']._serialized_end=278
  _globals['_QUESTTYPETABLEMGR']._serialized_start=281
  _globals['_QUESTTYPETABLEMGR']._serialized_end=427
  _globals['_QUESTTYPETABLEMGR_DATASENTRY']._serialized_start=355
  _globals['_QUESTTYPETABLEMGR_DATASENTRY']._serialized_end=427
# @@protoc_insertion_point(module_scope)
