# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QuickJumpTypeTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'QuickJumpTypeTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18QuickJumpTypeTable.proto\x12\x06\x62okura\"^\n\x16QuickJumpTypeTableBase\x12\r\n\x04Type\x18\xa1\x05 \x01(\x05\x12\x0e\n\x05Param\x18\xb7\t \x01(\t\x12\x10\n\x07\x45xample\x18\x8a\x04 \x01(\t\x12\x13\n\nRefreshNum\x18\xe0\n \x01(\t\"\x9e\x01\n\x15QuickJumpTypeTableMgr\x12\x37\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32(.bokura.QuickJumpTypeTableMgr.DatasEntry\x1aL\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.bokura.QuickJumpTypeTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QuickJumpTypeTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUICKJUMPTYPETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_QUICKJUMPTYPETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_QUICKJUMPTYPETABLEBASE']._serialized_start=36
  _globals['_QUICKJUMPTYPETABLEBASE']._serialized_end=130
  _globals['_QUICKJUMPTYPETABLEMGR']._serialized_start=133
  _globals['_QUICKJUMPTYPETABLEMGR']._serialized_end=291
  _globals['_QUICKJUMPTYPETABLEMGR_DATASENTRY']._serialized_start=215
  _globals['_QUICKJUMPTYPETABLEMGR_DATASENTRY']._serialized_end=291
# @@protoc_insertion_point(module_scope)
