# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RedDotIndexTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RedDotIndexTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RedDotIndexTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xc6\x02\n\x14RedDotIndexTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x13\n\nRedSignKey\x18\x98\x0e \x01(\t\x12\x13\n\nFunctionId\x18\x95\x01 \x01(\x05\x12\x1f\n\nCloseCheck\x18\xd3\x0e \x01(\x0b\x32\n.int_array\x12\x1e\n\tLoseCheck\x18\xcc\x04 \x01(\x0b\x32\n.int_array\x12\x1f\n\nChildrenID\x18\x83\t \x01(\x0b\x32\n.int_array\x12\x1d\n\x08ShowType\x18\xeb\x08 \x01(\x0b\x32\n.int_array\x12\x14\n\x0bPicturePath\x18\xb4\t \x01(\t\x12\x13\n\nEffectPath\x18\x80\x0c \x01(\t\x12\x1b\n\x06OffSet\x18\xfd\x03 \x01(\x0b\x32\n.int_array\x12\x19\n\x04Size\x18\xef\x08 \x01(\x0b\x32\n.int_array\x12\x13\n\nServerType\x18\xce\x05 \x01(\x05\"\x98\x01\n\x13RedDotIndexTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.RedDotIndexTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.RedDotIndexTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RedDotIndexTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REDDOTINDEXTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_REDDOTINDEXTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_REDDOTINDEXTABLEBASE']._serialized_start=54
  _globals['_REDDOTINDEXTABLEBASE']._serialized_end=380
  _globals['_REDDOTINDEXTABLEMGR']._serialized_start=383
  _globals['_REDDOTINDEXTABLEMGR']._serialized_end=535
  _globals['_REDDOTINDEXTABLEMGR_DATASENTRY']._serialized_start=461
  _globals['_REDDOTINDEXTABLEMGR_DATASENTRY']._serialized_end=535
# @@protoc_insertion_point(module_scope)
