# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SeasonCenterTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SeasonCenterTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17SeasonCenterTable.proto\x12\x06\x62okura\"P\n\x15SeasonCenterTableBase\x12\x13\n\nFunctionId\x18\x95\x01 \x01(\x05\x12\x13\n\nNameRemark\x18\xff\x0b \x01(\t\x12\r\n\x04Sort\x18\xeb\x0c \x01(\x05\"\x9b\x01\n\x14SeasonCenterTableMgr\x12\x36\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\'.bokura.SeasonCenterTableMgr.DatasEntry\x1aK\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.bokura.SeasonCenterTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SeasonCenterTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEASONCENTERTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_SEASONCENTERTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_SEASONCENTERTABLEBASE']._serialized_start=35
  _globals['_SEASONCENTERTABLEBASE']._serialized_end=115
  _globals['_SEASONCENTERTABLEMGR']._serialized_start=118
  _globals['_SEASONCENTERTABLEMGR']._serialized_end=273
  _globals['_SEASONCENTERTABLEMGR_DATASENTRY']._serialized_start=198
  _globals['_SEASONCENTERTABLEMGR_DATASENTRY']._serialized_end=273
# @@protoc_insertion_point(module_scope)
