# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serv_photograph_ntf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serv_photograph_ntf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_get_photo_token_ntf_request_pb2 as stru__get__photo__token__ntf__request__pb2
import stru_ret_avatar_token_request_pb2 as stru__ret__avatar__token__request__pb2
import stru_review_avatar_info_ntf_request_pb2 as stru__review__avatar__info__ntf__request__pb2
import stru_upload_photo_result_ntf_request_pb2 as stru__upload__photo__result__ntf__request__pb2
import stru_upload_picture_result_ntf_request_pb2 as stru__upload__picture__result__ntf__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19serv_photograph_ntf.proto\x12\x06zproto\x1a&stru_get_photo_token_ntf_request.proto\x1a#stru_ret_avatar_token_request.proto\x1a)stru_review_avatar_info_ntf_request.proto\x1a*stru_upload_photo_result_ntf_request.proto\x1a,stru_upload_picture_result_ntf_request.proto\"\x88\x03\n\rPhotographNtf\x1a\x45\n\x10GetPhotoTokenNtf\x12\x31\n\x08vRequest\x18\x01 \x01(\x0b\x32\x1f.zproto.GetPhotoTokenNtfRequest\x1aM\n\x14UploadPhotoResultNtf\x12\x35\n\x08vRequest\x18\x01 \x01(\x0b\x32#.zproto.UploadPhotoResultNtfRequest\x1aQ\n\x16UploadPictureResultNtf\x12\x37\n\x08vRequest\x18\x01 \x01(\x0b\x32%.zproto.UploadPictureResultNtfRequest\x1a\x41\n\x0eRetAvatarToken\x12/\n\x08vRequest\x18\x01 \x01(\x0b\x32\x1d.zproto.RetAvatarTokenRequest\x1aK\n\x13ReviewAvatarInfoNtf\x12\x34\n\x08vRequest\x18\x01 \x01(\x0b\x32\".zproto.ReviewAvatarInfoNtfRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serv_photograph_ntf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHOTOGRAPHNTF']._serialized_start=248
  _globals['_PHOTOGRAPHNTF']._serialized_end=640
  _globals['_PHOTOGRAPHNTF_GETPHOTOTOKENNTF']._serialized_start=265
  _globals['_PHOTOGRAPHNTF_GETPHOTOTOKENNTF']._serialized_end=334
  _globals['_PHOTOGRAPHNTF_UPLOADPHOTORESULTNTF']._serialized_start=336
  _globals['_PHOTOGRAPHNTF_UPLOADPHOTORESULTNTF']._serialized_end=413
  _globals['_PHOTOGRAPHNTF_UPLOADPICTURERESULTNTF']._serialized_start=415
  _globals['_PHOTOGRAPHNTF_UPLOADPICTURERESULTNTF']._serialized_end=496
  _globals['_PHOTOGRAPHNTF_RETAVATARTOKEN']._serialized_start=498
  _globals['_PHOTOGRAPHNTF_RETAVATARTOKEN']._serialized_end=563
  _globals['_PHOTOGRAPHNTF_REVIEWAVATARINFONTF']._serialized_start=565
  _globals['_PHOTOGRAPHNTF_REVIEWAVATARINFONTF']._serialized_end=640
# @@protoc_insertion_point(module_scope)
