# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serv_social_ntf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serv_social_ntf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_notify_social_data_request_pb2 as stru__notify__social__data__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15serv_social_ntf.proto\x12\x06zproto\x1a%stru_notify_social_data_request.proto\"R\n\tSocialNtf\x1a\x45\n\x10NotifySocialData\x12\x31\n\x08vRequest\x18\x01 \x01(\x0b\x32\x1f.zproto.NotifySocialDataRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serv_social_ntf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOCIALNTF']._serialized_start=72
  _globals['_SOCIALNTF']._serialized_end=154
  _globals['_SOCIALNTF_NOTIFYSOCIALDATA']._serialized_start=85
  _globals['_SOCIALNTF_NOTIFYSOCIALDATA']._serialized_end=154
# @@protoc_insertion_point(module_scope)
