# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SetKeyboardTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SetKeyboardTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SetKeyboardTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xd7\x01\n\x14SetKeyboardTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x1e\n\tActionIds\x18\x9f\r \x01(\x0b\x32\n.int_array\x12\x16\n\rMapCategoryId\x18\xdb\n \x01(\x05\x12\x1a\n\x06SetDes\x18\x93\x0f \x01(\x0b\x32\t.mlstring\x12\x14\n\x0bKeyboardDes\x18\xff\x02 \x01(\x05\x12\x13\n\nFunctionId\x18\x95\x01 \x01(\x05\x12\r\n\x04Sort\x18\xeb\x0c \x01(\x05\x12\x13\n\nShowSwitch\x18\xd7\x02 \x01(\x05\x12\x0f\n\x06GoBack\x18\xc1\x0c \x01(\t\"\x98\x01\n\x13SetKeyboardTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.SetKeyboardTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.SetKeyboardTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetKeyboardTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETKEYBOARDTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_SETKEYBOARDTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_SETKEYBOARDTABLEBASE']._serialized_start=54
  _globals['_SETKEYBOARDTABLEBASE']._serialized_end=269
  _globals['_SETKEYBOARDTABLEMGR']._serialized_start=272
  _globals['_SETKEYBOARDTABLEMGR']._serialized_end=424
  _globals['_SETKEYBOARDTABLEMGR_DATASENTRY']._serialized_start=350
  _globals['_SETKEYBOARDTABLEMGR_DATASENTRY']._serialized_end=424
# @@protoc_insertion_point(module_scope)
