# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_gasha_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_gasha_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_gasha_guarantee_info_pb2 as stru__gasha__guarantee__info__pb2
import stru_gasha_info_pb2 as stru__gasha__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_gasha_data.proto\x12\x06zproto\x1a\x1fstru_gasha_guarantee_info.proto\x1a\x15stru_gasha_info.proto\x1a\x15stru_dirty_mask.proto\"\xa9\x02\n\tGashaData\x12\x35\n\ngashaInfos\x18\x01 \x03(\x0b\x32!.zproto.GashaData.GashaInfosEntry\x12G\n\x13gashaGuaranteeInfos\x18\x02 \x03(\x0b\x32*.zproto.GashaData.GashaGuaranteeInfosEntry\x1a\x44\n\x0fGashaInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.zproto.GashaInfo:\x02\x38\x01\x1aV\n\x18GashaGuaranteeInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.zproto.GashaGuaranteeInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_gasha_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GASHADATA_GASHAINFOSENTRY']._loaded_options = None
  _globals['_GASHADATA_GASHAINFOSENTRY']._serialized_options = b'8\001'
  _globals['_GASHADATA_GASHAGUARANTEEINFOSENTRY']._loaded_options = None
  _globals['_GASHADATA_GASHAGUARANTEEINFOSENTRY']._serialized_options = b'8\001'
  _globals['_GASHADATA']._serialized_start=113
  _globals['_GASHADATA']._serialized_end=410
  _globals['_GASHADATA_GASHAINFOSENTRY']._serialized_start=254
  _globals['_GASHADATA_GASHAINFOSENTRY']._serialized_end=322
  _globals['_GASHADATA_GASHAGUARANTEEINFOSENTRY']._serialized_start=324
  _globals['_GASHADATA_GASHAGUARANTEEINFOSENTRY']._serialized_end=410
# @@protoc_insertion_point(module_scope)
