# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_monster_hunt_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_monster_hunt_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_monster_hunt_target_pb2 as stru__monster__hunt__target__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_monster_hunt_info.proto\x12\x06zproto\x1a\x1estru_monster_hunt_target.proto\x1a\x15stru_dirty_mask.proto\"\xda\x03\n\x0fMonsterHuntInfo\x12\x45\n\x0fmonsterHuntList\x18\x01 \x03(\x0b\x32,.zproto.MonsterHuntInfo.MonsterHuntListEntry\x12\x10\n\x08\x63urLevel\x18\x02 \x01(\x05\x12\x0e\n\x06\x63urExp\x18\x03 \x01(\x05\x12\x43\n\x0elevelAwardFlag\x18\x04 \x03(\x0b\x32+.zproto.MonsterHuntInfo.LevelAwardFlagEntry\x12Q\n\x15monsterHuntRefrshTime\x18\x06 \x03(\x0b\x32\x32.zproto.MonsterHuntInfo.MonsterHuntRefrshTimeEntry\x1aQ\n\x14MonsterHuntListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.zproto.MonsterHuntTarget:\x02\x38\x01\x1a\x35\n\x13LevelAwardFlagEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a<\n\x1aMonsterHuntRefrshTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_monster_hunt_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._loaded_options = None
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._loaded_options = None
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._loaded_options = None
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERHUNTINFO']._serialized_start=96
  _globals['_MONSTERHUNTINFO']._serialized_end=570
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._serialized_start=372
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._serialized_end=453
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._serialized_start=455
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._serialized_end=508
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._serialized_start=510
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._serialized_end=570
# @@protoc_insertion_point(module_scope)
