# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_fish_setting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_fish_setting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_fish_record_pb2 as stru__fish__record__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_fish_setting.proto\x12\x06zproto\x1a\x16stru_fish_record.proto\x1a\x15stru_dirty_mask.proto\"\xc3\x04\n\x0b\x46ishSetting\x12\x0e\n\x06\x62\x61itId\x18\x02 \x01(\x05\x12\x13\n\x0b\x65xperiences\x18\x03 \x01(\x05\x12\x16\n\x0eresearchFishId\x18\x04 \x01(\x05\x12\x39\n\x0b\x66ishRecords\x18\x05 \x03(\x0b\x32$.zproto.FishSetting.FishRecordsEntry\x12\x45\n\x11\x66ishRodDurability\x18\x06 \x03(\x0b\x32*.zproto.FishSetting.FishRodDurabilityEntry\x12\x0f\n\x07rodUuid\x18\x07 \x01(\x04\x12\x39\n\x0blevelReward\x18\x08 \x03(\x0b\x32$.zproto.FishSetting.LevelRewardEntry\x12=\n\rzeroFishTimes\x18\t \x03(\x0b\x32&.zproto.FishSetting.ZeroFishTimesEntry\x1a\x46\n\x10\x46ishRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.zproto.FishRecord:\x02\x38\x01\x1a\x38\n\x16\x46ishRodDurabilityEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10LevelRewardEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1a\x34\n\x12ZeroFishTimesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_fish_setting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FISHSETTING_FISHRECORDSENTRY']._loaded_options = None
  _globals['_FISHSETTING_FISHRECORDSENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._loaded_options = None
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING_LEVELREWARDENTRY']._loaded_options = None
  _globals['_FISHSETTING_LEVELREWARDENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._loaded_options = None
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING']._serialized_start=83
  _globals['_FISHSETTING']._serialized_end=662
  _globals['_FISHSETTING_FISHRECORDSENTRY']._serialized_start=428
  _globals['_FISHSETTING_FISHRECORDSENTRY']._serialized_end=498
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._serialized_start=500
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._serialized_end=556
  _globals['_FISHSETTING_LEVELREWARDENTRY']._serialized_start=558
  _globals['_FISHSETTING_LEVELREWARDENTRY']._serialized_end=608
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._serialized_start=610
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._serialized_end=662
# @@protoc_insertion_point(module_scope)
