# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_scene_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_scene_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_last_scene_data_pb2 as stru__last__scene__data__pb2
import stru_position_pb2 as stru__position__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_scene_data.proto\x12\x06zproto\x1a\x1astru_last_scene_data.proto\x1a\x13stru_position.proto\x1a\x15stru_dirty_mask.proto\"\xc4\x04\n\tSceneData\x12\r\n\x05mapId\x18\x01 \x01(\r\x12\x11\n\tchannelId\x18\x02 \x01(\r\x12\x1d\n\x03pos\x18\x03 \x01(\x0b\x32\x10.zproto.Position\x12\x11\n\tlevelUuid\x18\x04 \x01(\x03\x12\"\n\x08levelPos\x18\x05 \x01(\x0b\x32\x10.zproto.Position\x12\x12\n\nlevelMapId\x18\x06 \x01(\r\x12\x15\n\rlevelReviveId\x18\x07 \x01(\r\x12\x31\n\x08recordId\x18\x08 \x03(\x0b\x32\x1f.zproto.SceneData.RecordIdEntry\x12\x0f\n\x07planeId\x18\t \x01(\r\x12\x12\n\nsceneLayer\x18\n \x01(\r\x12\x16\n\x0e\x63\x61nSwitchLayer\x18\x0b \x01(\x08\x12\'\n\rbeforeFallPos\x18\x0c \x01(\x0b\x32\x10.zproto.Position\x12\x11\n\tsceneGuid\x18\r \x01(\t\x12\x13\n\x0b\x64ungeonGuid\x18\x0e \x01(\t\x12\x0e\n\x06lineId\x18\x0f \x01(\r\x12\x1b\n\x13visualLayerConfigId\x18\x10 \x01(\r\x12,\n\rlastSceneData\x18\x11 \x01(\x0b\x32\x15.zproto.LastSceneData\x12\x13\n\x0bsceneAreaId\x18\x12 \x01(\x05\x12\x13\n\x0blevelAreaId\x18\x13 \x01(\x05\x12\x1d\n\x15\x62\x65\x66oreFallSceneAreaId\x18\x14 \x01(\x05\x1a/\n\rRecordIdEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_scene_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENEDATA_RECORDIDENTRY']._loaded_options = None
  _globals['_SCENEDATA_RECORDIDENTRY']._serialized_options = b'8\001'
  _globals['_SCENEDATA']._serialized_start=106
  _globals['_SCENEDATA']._serialized_end=686
  _globals['_SCENEDATA_RECORDIDENTRY']._serialized_start=639
  _globals['_SCENEDATA_RECORDIDENTRY']._serialized_end=686
# @@protoc_insertion_point(module_scope)
