# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_gasha_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_gasha_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_gasha_info.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"\xa5\x01\n\tGashaInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\tdrawCount\x18\x04 \x01(\r\x12\x13\n\x0brefreshTime\x18\x05 \x01(\x03\x12\x0e\n\x06wishId\x18\x08 \x01(\r\x12\x11\n\twishValue\x18\t \x01(\r\x12\x17\n\x0fwishFinishCount\x18\n \x01(\r\x12\x15\n\rwishResetTime\x18\x0b \x01(\x03\x12\x11\n\twishLimit\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_gasha_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GASHAINFO']._serialized_start=57
  _globals['_GASHAINFO']._serialized_end=222
# @@protoc_insertion_point(module_scope)
