# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_lif_profession_point_tips_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_lif_profession_point_tips_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_item_get_opt_src_pb2 as enum__e__item__get__opt__src__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)stru_lif_profession_point_tips_info.proto\x12\x06zproto\x1a\x1d\x65num_e_item_get_opt_src.proto\"|\n\x1aLifProfessionPointTipsInfo\x12\x30\n\x10getLifePointType\x18\x01 \x01(\x0e\x32\x16.zproto.EItemGetOptSrc\x12\x18\n\x10lifeProfessionId\x18\x02 \x01(\r\x12\x12\n\npointCount\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_lif_profession_point_tips_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIFPROFESSIONPOINTTIPSINFO']._serialized_start=84
  _globals['_LIFPROFESSIONPOINTTIPSINFO']._serialized_end=208
# @@protoc_insertion_point(module_scope)
