# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_user_fight_attr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_user_fight_attr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_skill_c_d_info_pb2 as stru__skill__c__d__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astru_user_fight_attr.proto\x12\x06zproto\x1a\x19stru_skill_c_d_info.proto\x1a\x15stru_dirty_mask.proto\"\xc4\x01\n\rUserFightAttr\x12\r\n\x05\x63urHp\x18\x01 \x01(\x03\x12\r\n\x05maxHp\x18\x02 \x01(\x03\x12\x14\n\x0coriginEnergy\x18\x03 \x01(\x02\x12\x13\n\x0bresourceIds\x18\x04 \x03(\r\x12\x11\n\tresources\x18\x05 \x03(\r\x12\x0e\n\x06isDead\x18\x06 \x01(\x05\x12\x10\n\x08\x64\x65\x61\x64Time\x18\x07 \x01(\x03\x12\x10\n\x08reviveId\x18\x08 \x01(\x05\x12#\n\x06\x63\x64Info\x18\t \x03(\x0b\x32\x13.zproto.SkillCDInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_user_fight_attr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERFIGHTATTR']._serialized_start=89
  _globals['_USERFIGHTATTR']._serialized_end=285
# @@protoc_insertion_point(module_scope)
