# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_item_currency.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_item_currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_currency_data_pb2 as stru__currency__data__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_item_currency.proto\x12\x06zproto\x1a\x18stru_currency_data.proto\x1a\x15stru_dirty_mask.proto\"\xaa\x01\n\x0cItemCurrency\x12\x0e\n\x06isInit\x18\x01 \x01(\x08\x12>\n\rcurrencyDatas\x18\x02 \x03(\x0b\x32\'.zproto.ItemCurrency.CurrencyDatasEntry\x1aJ\n\x12\x43urrencyDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zproto.CurrencyData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_item_currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMCURRENCY_CURRENCYDATASENTRY']._loaded_options = None
  _globals['_ITEMCURRENCY_CURRENCYDATASENTRY']._serialized_options = b'8\001'
  _globals['_ITEMCURRENCY']._serialized_start=86
  _globals['_ITEMCURRENCY']._serialized_end=256
  _globals['_ITEMCURRENCY_CURRENCYDATASENTRY']._serialized_start=182
  _globals['_ITEMCURRENCY_CURRENCYDATASENTRY']._serialized_end=256
# @@protoc_insertion_point(module_scope)
