# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_handbook_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_handbook_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_hand_book_struct_pb2 as stru__hand__book__struct__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_handbook_data.proto\x12\x06zproto\x1a\x1bstru_hand_book_struct.proto\x1a\x15stru_dirty_mask.proto\"\xed\x06\n\x0cHandbookData\x12X\n\x1aunlockNoteImportantRoleMap\x18\x01 \x03(\x0b\x32\x34.zproto.HandbookData.UnlockNoteImportantRoleMapEntry\x12T\n\x18unlockNoteReadingBookMap\x18\x02 \x03(\x0b\x32\x32.zproto.HandbookData.UnlockNoteReadingBookMapEntry\x12R\n\x17unlockNoteDictionaryMap\x18\x03 \x03(\x0b\x32\x31.zproto.HandbookData.UnlockNoteDictionaryMapEntry\x12N\n\x15unlockNotePostCardMap\x18\x04 \x03(\x0b\x32/.zproto.HandbookData.UnlockNotePostCardMapEntry\x12P\n\x16unlockNoteMonthCardMap\x18\x05 \x03(\x0b\x32\x30.zproto.HandbookData.UnlockNoteMonthCardMapEntry\x1aY\n\x1fUnlockNoteImportantRoleMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.HandBookStruct:\x02\x38\x01\x1aW\n\x1dUnlockNoteReadingBookMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.HandBookStruct:\x02\x38\x01\x1aV\n\x1cUnlockNoteDictionaryMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.HandBookStruct:\x02\x38\x01\x1aT\n\x1aUnlockNotePostCardMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.HandBookStruct:\x02\x38\x01\x1aU\n\x1bUnlockNoteMonthCardMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.HandBookStruct:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_handbook_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDBOOKDATA_UNLOCKNOTEIMPORTANTROLEMAPENTRY']._loaded_options = None
  _globals['_HANDBOOKDATA_UNLOCKNOTEIMPORTANTROLEMAPENTRY']._serialized_options = b'8\001'
  _globals['_HANDBOOKDATA_UNLOCKNOTEREADINGBOOKMAPENTRY']._loaded_options = None
  _globals['_HANDBOOKDATA_UNLOCKNOTEREADINGBOOKMAPENTRY']._serialized_options = b'8\001'
  _globals['_HANDBOOKDATA_UNLOCKNOTEDICTIONARYMAPENTRY']._loaded_options = None
  _globals['_HANDBOOKDATA_UNLOCKNOTEDICTIONARYMAPENTRY']._serialized_options = b'8\001'
  _globals['_HANDBOOKDATA_UNLOCKNOTEPOSTCARDMAPENTRY']._loaded_options = None
  _globals['_HANDBOOKDATA_UNLOCKNOTEPOSTCARDMAPENTRY']._serialized_options = b'8\001'
  _globals['_HANDBOOKDATA_UNLOCKNOTEMONTHCARDMAPENTRY']._loaded_options = None
  _globals['_HANDBOOKDATA_UNLOCKNOTEMONTHCARDMAPENTRY']._serialized_options = b'8\001'
  _globals['_HANDBOOKDATA']._serialized_start=89
  _globals['_HANDBOOKDATA']._serialized_end=966
  _globals['_HANDBOOKDATA_UNLOCKNOTEIMPORTANTROLEMAPENTRY']._serialized_start=527
  _globals['_HANDBOOKDATA_UNLOCKNOTEIMPORTANTROLEMAPENTRY']._serialized_end=616
  _globals['_HANDBOOKDATA_UNLOCKNOTEREADINGBOOKMAPENTRY']._serialized_start=618
  _globals['_HANDBOOKDATA_UNLOCKNOTEREADINGBOOKMAPENTRY']._serialized_end=705
  _globals['_HANDBOOKDATA_UNLOCKNOTEDICTIONARYMAPENTRY']._serialized_start=707
  _globals['_HANDBOOKDATA_UNLOCKNOTEDICTIONARYMAPENTRY']._serialized_end=793
  _globals['_HANDBOOKDATA_UNLOCKNOTEPOSTCARDMAPENTRY']._serialized_start=795
  _globals['_HANDBOOKDATA_UNLOCKNOTEPOSTCARDMAPENTRY']._serialized_end=879
  _globals['_HANDBOOKDATA_UNLOCKNOTEMONTHCARDMAPENTRY']._serialized_start=881
  _globals['_HANDBOOKDATA_UNLOCKNOTEMONTHCARDMAPENTRY']._serialized_end=966
# @@protoc_insertion_point(module_scope)
