# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mail_base.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mail_base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_item_pb2 as stru__item__pb2
import stru_mail_extra_condition_pb2 as stru__mail__extra__condition__pb2
import enum_mail_state_pb2 as enum__mail__state__pb2
import enum_mail_type_pb2 as enum__mail__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stru_mail_base.proto\x12\x06zproto\x1a\x0fstru_item.proto\x1a\x1fstru_mail_extra_condition.proto\x1a\x15\x65num_mail_state.proto\x1a\x14\x65num_mail_type.proto\"\xc7\x03\n\x08MailBase\x12\x10\n\x08mailUuid\x18\x01 \x01(\x03\x12\x14\n\x0cmailConfigId\x18\x02 \x01(\r\x12\x12\n\ncreateTime\x18\x03 \x01(\x03\x12\"\n\x08mailType\x18\x04 \x01(\x0e\x32\x10.zproto.MailType\x12\x0e\n\x06sendId\x18\x05 \x01(\x03\x12\x10\n\x08sendName\x18\x06 \x01(\t\x12\x11\n\tmailTitle\x18\x07 \x01(\t\x12\x10\n\x08mailBody\x18\x08 \x01(\t\x12\x11\n\ttimeoutMs\x18\t \x01(\x03\x12\x1e\n\x08\x61ppendix\x18\n \x03(\x0b\x32\x0c.zproto.Item\x12$\n\tmailState\x18\x0b \x01(\x0e\x32\x11.zproto.MailState\x12\x12\n\ntitlePrams\x18\x0c \x03(\t\x12\x11\n\tbodyPrams\x18\r \x03(\t\x12\x10\n\x08\x61\x63\x63\x65ptId\x18\x0e \x01(\x03\x12\x12\n\nimportance\x18\x0f \x01(\r\x12\x10\n\x08\x61wardIds\x18\x10 \x03(\r\x12\x1a\n\x12RegisterBeforeTime\x18\x11 \x01(\x03\x12-\n\tcondition\x18\x12 \x01(\x0b\x32\x1a.zproto.MailExtraCondition\x12\x11\n\tisCollect\x18\x13 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mail_base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAILBASE']._serialized_start=128
  _globals['_MAILBASE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
