# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_compensation_statistics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_compensation_statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_compensation_season_statistics_pb2 as stru__compensation__season__statistics__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"stru_compensation_statistics.proto\x12\x06zproto\x1a)stru_compensation_season_statistics.proto\x1a\x15stru_dirty_mask.proto\"\xe0\x02\n\x16\x43ompensationStatistics\x12\x42\n\nseasonData\x18\x01 \x03(\x0b\x32..zproto.CompensationStatistics.SeasonDataEntry\x12\x14\n\x0clastSeasonId\x18\x02 \x01(\r\x12\x10\n\x08\x63urPoint\x18\x03 \x01(\x03\x12\x10\n\x08maxPoint\x18\x04 \x01(\x03\x12>\n\x08lastWeek\x18\x05 \x03(\x0b\x32,.zproto.CompensationStatistics.LastWeekEntry\x1aW\n\x0fSeasonDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.zproto.CompensationSeasonStatistics:\x02\x38\x01\x1a/\n\rLastWeekEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_compensation_statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPENSATIONSTATISTICS_SEASONDATAENTRY']._loaded_options = None
  _globals['_COMPENSATIONSTATISTICS_SEASONDATAENTRY']._serialized_options = b'8\001'
  _globals['_COMPENSATIONSTATISTICS_LASTWEEKENTRY']._loaded_options = None
  _globals['_COMPENSATIONSTATISTICS_LASTWEEKENTRY']._serialized_options = b'8\001'
  _globals['_COMPENSATIONSTATISTICS']._serialized_start=113
  _globals['_COMPENSATIONSTATISTICS']._serialized_end=465
  _globals['_COMPENSATIONSTATISTICS_SEASONDATAENTRY']._serialized_start=329
  _globals['_COMPENSATIONSTATISTICS_SEASONDATAENTRY']._serialized_end=416
  _globals['_COMPENSATIONSTATISTICS_LASTWEEKENTRY']._serialized_start=418
  _globals['_COMPENSATIONSTATISTICS_LASTWEEKENTRY']._serialized_end=465
# @@protoc_insertion_point(module_scope)
