# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_interaction_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_interaction_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstru_interaction_info.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"\x95\x01\n\x0fInteractionInfo\x12\x18\n\x10interactionStage\x18\x01 \x01(\x05\x12\x10\n\x08\x61\x63tionId\x18\x02 \x01(\x05\x12\x14\n\x0coriginatorId\x18\x03 \x01(\x03\x12\x11\n\tinviteeId\x18\x04 \x01(\x03\x12\x14\n\x0cisOriginator\x18\x05 \x01(\x08\x12\x17\n\x0finteractionType\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_interaction_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERACTIONINFO']._serialized_start=63
  _globals['_INTERACTIONINFO']._serialized_end=212
# @@protoc_insertion_point(module_scope)
