# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mem_union_activity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mem_union_activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_not_claimed_reward_pb2 as stru__not__claimed__reward__pb2
import stru_union_activity_target_pb2 as stru__union__activity__target__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_mem_union_activity.proto\x12\x06zproto\x1a\x1dstru_not_claimed_reward.proto\x1a stru_union_activity_target.proto\"\xb9\x02\n\x10MemUnionActivity\x12\x17\n\x0flastRefreshTime\x18\x01 \x01(\x03\x12\x46\n\x0fpersonalTargets\x18\x02 \x03(\x0b\x32-.zproto.MemUnionActivity.PersonalTargetsEntry\x12\x1d\n\x15receivedPointAwardIds\x18\x03 \x03(\x05\x12\x37\n\x15noClaimedActiveAwards\x18\x04 \x03(\x0b\x32\x18.zproto.NotClaimedReward\x12\x17\n\x0fnextRefreshTime\x18\x05 \x01(\x03\x1aS\n\x14PersonalTargetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.zproto.UnionActivityTarget:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mem_union_activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMUNIONACTIVITY_PERSONALTARGETSENTRY']._loaded_options = None
  _globals['_MEMUNIONACTIVITY_PERSONALTARGETSENTRY']._serialized_options = b'8\001'
  _globals['_MEMUNIONACTIVITY']._serialized_start=107
  _globals['_MEMUNIONACTIVITY']._serialized_end=420
  _globals['_MEMUNIONACTIVITY_PERSONALTARGETSENTRY']._serialized_start=337
  _globals['_MEMUNIONACTIVITY_PERSONALTARGETSENTRY']._serialized_end=420
# @@protoc_insertion_point(module_scope)
