# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_fashion_benefit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_fashion_benefit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_fashion_benefit_collection_history_pb2 as stru__fashion__benefit__collection__history__pb2
import stru_fashion_benefit_task_info_pb2 as stru__fashion__benefit__task__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astru_fashion_benefit.proto\x12\x06zproto\x1a-stru_fashion_benefit_collection_history.proto\x1a$stru_fashion_benefit_task_info.proto\x1a\x15stru_dirty_mask.proto\"\xf6\x03\n\x0e\x46\x61shionBenefit\x12\x14\n\x0clastRewardId\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x12\n\npointsTask\x18\x03 \x01(\x05\x12\x13\n\x0bpointsCycle\x18\x04 \x01(\x05\x12\x18\n\x10pointsCollection\x18\x05 \x01(\x05\x12\x36\n\x08taskList\x18\x06 \x03(\x0b\x32$.zproto.FashionBenefit.TaskListEntry\x12\x42\n\x11\x63ollectionHistory\x18\x07 \x03(\x0b\x32\'.zproto.FashionBenefitCollectionHistory\x12\x17\n\x0fnextRefreshTime\x18\x08 \x01(\x03\x12\x11\n\tmaxPoints\x18\t \x01(\x05\x12\x13\n\x0blastAddTime\x18\n \x01(\x03\x12\x17\n\x0f\x63urDayMaxPoints\x18\x0b \x01(\x05\x12\x13\n\x0b\x65xpireCycle\x18\x0c \x01(\x05\x12\x11\n\tlastLevel\x18\r \x01(\x05\x12\x16\n\x0e\x66irtExpireTime\x18\x0e \x01(\x03\x12\x15\n\rlastRewardIds\x18\x0f \x03(\x05\x1aO\n\rTaskListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.zproto.FashionBenefitTaskInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_fashion_benefit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FASHIONBENEFIT_TASKLISTENTRY']._loaded_options = None
  _globals['_FASHIONBENEFIT_TASKLISTENTRY']._serialized_options = b'8\001'
  _globals['_FASHIONBENEFIT']._serialized_start=147
  _globals['_FASHIONBENEFIT']._serialized_end=649
  _globals['_FASHIONBENEFIT_TASKLISTENTRY']._serialized_start=570
  _globals['_FASHIONBENEFIT_TASKLISTENTRY']._serialized_end=649
# @@protoc_insertion_point(module_scope)
