# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_monthly_card_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_monthly_card_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_receive_reward_status_pb2 as enum__e__receive__reward__status__pb2
import stru_month_card_item_pb2 as stru__month__card__item__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_monthly_card_info.proto\x12\x06zproto\x1a\"enum_e_receive_reward_status.proto\x1a\x1astru_month_card_item.proto\x1a\x15stru_dirty_mask.proto\"\xce\x01\n\x0fMonthlyCardInfo\x12\x36\n\x10limitAwardStatus\x18\x01 \x01(\x0e\x32\x1c.zproto.EReceiveRewardStatus\x12\x31\n\x0b\x61wardStatus\x18\x02 \x01(\x0e\x32\x1c.zproto.EReceiveRewardStatus\x12,\n\rmonthCardItem\x18\x03 \x01(\x0b\x32\x15.zproto.MonthCardItem\x12\x11\n\tbeginTime\x18\x04 \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_monthly_card_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONTHLYCARDINFO']._serialized_start=128
  _globals['_MONTHLYCARDINFO']._serialized_end=334
# @@protoc_insertion_point(module_scope)
