# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_season_activation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_season_activation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_season_activation_target_pb2 as stru__season__activation__target__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_season_activation.proto\x12\x06zproto\x1a#stru_season_activation_target.proto\x1a\x15stru_dirty_mask.proto\"\xfe\x02\n\x10SeasonActivation\x12\x10\n\x08seasonId\x18\x01 \x01(\x05\x12\x17\n\x0f\x61\x63tivationPoint\x18\x02 \x01(\x05\x12\x13\n\x0brefreshTime\x18\x03 \x01(\x05\x12J\n\x11\x61\x63tivationTargets\x18\x04 \x03(\x0b\x32/.zproto.SeasonActivation.ActivationTargetsEntry\x12J\n\x11stageRewardStatus\x18\x05 \x03(\x0b\x32/.zproto.SeasonActivation.StageRewardStatusEntry\x1aX\n\x16\x41\x63tivationTargetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.zproto.SeasonActivationTarget:\x02\x38\x01\x1a\x38\n\x16StageRewardStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_season_activation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEASONACTIVATION_ACTIVATIONTARGETSENTRY']._loaded_options = None
  _globals['_SEASONACTIVATION_ACTIVATIONTARGETSENTRY']._serialized_options = b'8\001'
  _globals['_SEASONACTIVATION_STAGEREWARDSTATUSENTRY']._loaded_options = None
  _globals['_SEASONACTIVATION_STAGEREWARDSTATUSENTRY']._serialized_options = b'8\001'
  _globals['_SEASONACTIVATION']._serialized_start=101
  _globals['_SEASONACTIVATION']._serialized_end=483
  _globals['_SEASONACTIVATION_ACTIVATIONTARGETSENTRY']._serialized_start=337
  _globals['_SEASONACTIVATION_ACTIVATIONTARGETSENTRY']._serialized_end=425
  _globals['_SEASONACTIVATION_STAGEREWARDSTATUSENTRY']._serialized_start=427
  _globals['_SEASONACTIVATION_STAGEREWARDSTATUSENTRY']._serialized_end=483
# @@protoc_insertion_point(module_scope)
