# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_activity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_activity_award_pb2 as stru__activity__award__pb2
import enum_e_activity_status_pb2 as enum__e__activity__status__pb2
import enum_e_activity_type_pb2 as enum__e__activity__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stru_activity.proto\x12\x06zproto\x1a\x19stru_activity_award.proto\x1a\x1c\x65num_e_activity_status.proto\x1a\x1a\x65num_e_activity_type.proto\"\x8e\x04\n\x08\x41\x63tivity\x12\x14\n\x0c\x61\x63tivityUuid\x18\x01 \x01(\x03\x12\x18\n\x10\x61\x63tivityConfigId\x18\x02 \x01(\r\x12\x38\n\x0c\x61\x63tivityName\x18\x03 \x03(\x0b\x32\".zproto.Activity.ActivityNameEntry\x12+\n\x0c\x61\x63tivityType\x18\x04 \x01(\x0e\x32\x15.zproto.EActivityType\x12\x11\n\tstartTime\x18\x05 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x06 \x01(\x04\x12,\n\x06notice\x18\x08 \x03(\x0b\x32\x1c.zproto.Activity.NoticeEntry\x12\x0f\n\x07orderId\x18\t \x01(\x05\x12\'\n\x06status\x18\n \x01(\x0e\x32\x17.zproto.EActivityStatus\x12\x32\n\tawardList\x18\x0b \x03(\x0b\x32\x1f.zproto.Activity.AwardListEntry\x1a\x33\n\x11\x41\x63tivityNameEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bNoticeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aG\n\x0e\x41wardListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.zproto.ActivityAward:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVITY_ACTIVITYNAMEENTRY']._loaded_options = None
  _globals['_ACTIVITY_ACTIVITYNAMEENTRY']._serialized_options = b'8\001'
  _globals['_ACTIVITY_NOTICEENTRY']._loaded_options = None
  _globals['_ACTIVITY_NOTICEENTRY']._serialized_options = b'8\001'
  _globals['_ACTIVITY_AWARDLISTENTRY']._loaded_options = None
  _globals['_ACTIVITY_AWARDLISTENTRY']._serialized_options = b'8\001'
  _globals['_ACTIVITY']._serialized_start=117
  _globals['_ACTIVITY']._serialized_end=643
  _globals['_ACTIVITY_ACTIVITYNAMEENTRY']._serialized_start=472
  _globals['_ACTIVITY_ACTIVITYNAMEENTRY']._serialized_end=523
  _globals['_ACTIVITY_NOTICEENTRY']._serialized_start=525
  _globals['_ACTIVITY_NOTICEENTRY']._serialized_end=570
  _globals['_ACTIVITY_AWARDLISTENTRY']._serialized_start=572
  _globals['_ACTIVITY_AWARDLISTENTRY']._serialized_end=643
# @@protoc_insertion_point(module_scope)
