# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mod_attr_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mod_attr_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_mod_attr_info.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"\xb1\x01\n\x0bModAttrInfo\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\x12\x41\n\x0f\x65\x66\x66\x65\x63tParameter\x18\x04 \x03(\x0b\x32(.zproto.ModAttrInfo.EffectParameterEntry\x1a\x36\n\x14\x45\x66\x66\x65\x63tParameterEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mod_attr_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODATTRINFO_EFFECTPARAMETERENTRY']._loaded_options = None
  _globals['_MODATTRINFO_EFFECTPARAMETERENTRY']._serialized_options = b'8\001'
  _globals['_MODATTRINFO']._serialized_start=60
  _globals['_MODATTRINFO']._serialized_end=237
  _globals['_MODATTRINFO_EFFECTPARAMETERENTRY']._serialized_start=183
  _globals['_MODATTRINFO_EFFECTPARAMETERENTRY']._serialized_end=237
# @@protoc_insertion_point(module_scope)
