# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_server_state_object_interaction_param.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_server_state_object_interaction_param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0stru_server_state_object_interaction_param.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"e\n!ServerStateObjectInteractionParam\x12\x0f\n\x07objUuid\x18\x01 \x01(\x03\x12\x12\n\nstateValue\x18\x02 \x01(\x05\x12\x1b\n\x13lastInteractionTime\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_server_state_object_interaction_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERSTATEOBJECTINTERACTIONPARAM']._serialized_start=83
  _globals['_SERVERSTATEOBJECTINTERACTIONPARAM']._serialized_end=184
# @@protoc_insertion_point(module_scope)
