# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_friendliness.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_friendliness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_friendliness.proto\x12\x06zproto\"\xf8\x01\n\x0c\x46riendliness\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x0e\n\x06\x63urExp\x18\x02 \x01(\x05\x12\x17\n\x0fupdateTimeStamp\x18\x03 \x01(\x03\x12\x19\n\x11todayTotalAddExps\x18\x04 \x01(\x05\x12\x44\n\x10todayPartAddExps\x18\x05 \x03(\x0b\x32*.zproto.Friendliness.TodayPartAddExpsEntry\x12\x16\n\x0egotLevelAwards\x18\x06 \x03(\x05\x1a\x37\n\x15TodayPartAddExpsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_friendliness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIENDLINESS_TODAYPARTADDEXPSENTRY']._loaded_options = None
  _globals['_FRIENDLINESS_TODAYPARTADDEXPSENTRY']._serialized_options = b'8\001'
  _globals['_FRIENDLINESS']._serialized_start=36
  _globals['_FRIENDLINESS']._serialized_end=284
  _globals['_FRIENDLINESS_TODAYPARTADDEXPSENTRY']._serialized_start=229
  _globals['_FRIENDLINESS_TODAYPARTADDEXPSENTRY']._serialized_end=284
# @@protoc_insertion_point(module_scope)
