# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_user_union.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_user_union.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_union_dance_history_pb2 as stru__union__dance__history__pb2
import stru_union_history_active_pb2 as stru__union__history__active__pb2
import stru_user_union_hunt_info_pb2 as stru__user__union__hunt__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_user_union.proto\x12\x06zproto\x1a\x1estru_union_dance_history.proto\x1a\x1fstru_union_history_active.proto\x1a\x1fstru_user_union_hunt_info.proto\x1a\x15stru_dirty_mask.proto\"\xf4\x03\n\tUserUnion\x12\x0f\n\x07unionId\x18\x01 \x01(\x03\x12\x14\n\x0cnextJoinTime\x18\x02 \x01(\x04\x12;\n\rreqUnionTimes\x18\x03 \x03(\x0b\x32$.zproto.UserUnion.ReqUnionTimesEntry\x12\x10\n\x08joinFlag\x18\x04 \x01(\x08\x12\x14\n\x0c\x63ollectedIds\x18\x05 \x03(\x03\x12\x1c\n\x14\x61\x63tiveAwardResetTime\x18\x06 \x01(\x03\x12\x18\n\x10receivedAwardIds\x18\x07 \x03(\x05\x12\x37\n\x13historyActivePoints\x18\x08 \x03(\x0b\x32\x1a.zproto.UnionHistoryActive\x12\x1d\n\x15\x61\x63tiveLastRefreshTime\x18\t \x01(\x03\x12\x1c\n\x14\x66inishDailyActiveIds\x18\n \x03(\x05\x12\x11\n\tleaveTime\x18\x0b \x01(\x04\x12.\n\x0b\x64\x61nceRecord\x18\r \x01(\x0b\x32\x19.zproto.UnionDanceHistory\x12\x34\n\x11userUnionHuntInfo\x18\x0e \x01(\x0b\x32\x19.zproto.UserUnionHuntInfo\x1a\x34\n\x12ReqUnionTimesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_user_union_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERUNION_REQUNIONTIMESENTRY']._loaded_options = None
  _globals['_USERUNION_REQUNIONTIMESENTRY']._serialized_options = b'8\001'
  _globals['_USERUNION']._serialized_start=155
  _globals['_USERUNION']._serialized_end=655
  _globals['_USERUNION_REQUNIONTIMESENTRY']._serialized_start=603
  _globals['_USERUNION_REQUNIONTIMESENTRY']._serialized_end=655
# @@protoc_insertion_point(module_scope)
