# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mod.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_mod_info_pb2 as stru__mod__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estru_mod.proto\x12\x06zproto\x1a\x13stru_mod_info.proto\x1a\x15stru_dirty_mask.proto\"\xd2\x01\n\x03Mod\x12+\n\x08modSlots\x18\x01 \x03(\x0b\x32\x19.zproto.Mod.ModSlotsEntry\x12+\n\x08modInfos\x18\x02 \x03(\x0b\x32\x19.zproto.Mod.ModInfosEntry\x1a/\n\rModSlotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x1a@\n\rModInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.zproto.ModInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOD_MODSLOTSENTRY']._loaded_options = None
  _globals['_MOD_MODSLOTSENTRY']._serialized_options = b'8\001'
  _globals['_MOD_MODINFOSENTRY']._loaded_options = None
  _globals['_MOD_MODINFOSENTRY']._serialized_options = b'8\001'
  _globals['_MOD']._serialized_start=71
  _globals['_MOD']._serialized_end=281
  _globals['_MOD_MODSLOTSENTRY']._serialized_start=168
  _globals['_MOD_MODSLOTSENTRY']._serialized_end=215
  _globals['_MOD_MODINFOSENTRY']._serialized_start=217
  _globals['_MOD_MODINFOSENTRY']._serialized_end=281
# @@protoc_insertion_point(module_scope)
