# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_world_boss_settlement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_world_boss_settlement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dungeon_award_pb2 as stru__dungeon__award__pb2
import stru_dungeon_boss_rank_pb2 as stru__dungeon__boss__rank__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(stru_dungeon_world_boss_settlement.proto\x12\x06zproto\x1a\x18stru_dungeon_award.proto\x1a\x1cstru_dungeon_boss_rank.proto\x1a\x15stru_dirty_mask.proto\"\x98\x04\n\x1a\x44ungeonWorldBossSettlement\x12\x15\n\rbossHpPercent\x18\x01 \x01(\x05\x12\x30\n\x0f\x64ungeonBossRank\x18\x02 \x01(\x0b\x32\x17.zproto.DungeonBossRank\x12<\n\x05\x61ward\x18\x03 \x03(\x0b\x32-.zproto.DungeonWorldBossSettlement.AwardEntry\x12L\n\rbossRankAward\x18\x04 \x03(\x0b\x32\x35.zproto.DungeonWorldBossSettlement.BossRankAwardEntry\x12J\n\x0clastHitAward\x18\x05 \x03(\x0b\x32\x34.zproto.DungeonWorldBossSettlement.LastHitAwardEntry\x1a\x42\n\nAwardEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zproto.DungeonAward:\x02\x38\x01\x1aJ\n\x12\x42ossRankAwardEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zproto.DungeonAward:\x02\x38\x01\x1aI\n\x11LastHitAwardEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zproto.DungeonAward:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_world_boss_settlement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_AWARDENTRY']._loaded_options = None
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_AWARDENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_BOSSRANKAWARDENTRY']._loaded_options = None
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_BOSSRANKAWARDENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_LASTHITAWARDENTRY']._loaded_options = None
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_LASTHITAWARDENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONWORLDBOSSSETTLEMENT']._serialized_start=132
  _globals['_DUNGEONWORLDBOSSSETTLEMENT']._serialized_end=668
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_AWARDENTRY']._serialized_start=451
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_AWARDENTRY']._serialized_end=517
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_BOSSRANKAWARDENTRY']._serialized_start=519
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_BOSSRANKAWARDENTRY']._serialized_end=593
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_LASTHITAWARDENTRY']._serialized_start=595
  _globals['_DUNGEONWORLDBOSSSETTLEMENT_LASTHITAWARDENTRY']._serialized_end=668
# @@protoc_insertion_point(module_scope)
