# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_life_profession_alchemy_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_life_profession_alchemy_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'stru_life_profession_alchemy_info.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"Y\n\x19LifeProfessionAlchemyInfo\x12\x14\n\x0c\x66\x61ilureCount\x18\x01 \x01(\r\x12\x0f\n\x07rdCount\x18\x02 \x01(\r\x12\x15\n\rlastResetTime\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_life_profession_alchemy_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIFEPROFESSIONALCHEMYINFO']._serialized_start=74
  _globals['_LIFEPROFESSIONALCHEMYINFO']._serialized_end=163
# @@protoc_insertion_point(module_scope)
