# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_freight_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_freight_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_freight_data.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"\xb4\x01\n\x0b\x46reightData\x12\x13\n\x0brefreshTime\x18\x01 \x01(\x03\x12\x12\n\ngoodsValue\x18\x02 \x01(\x05\x12\x0e\n\x06setOff\x18\x03 \x01(\x08\x12\x12\n\ncanReceive\x18\x04 \x01(\x08\x12\x13\n\x0bupGoodsList\x18\x05 \x03(\x05\x12\x15\n\rkeepGoodsList\x18\x06 \x03(\x05\x12\x15\n\rdownGoodsList\x18\x07 \x03(\x05\x12\x15\n\rcanRewardTime\x18\x08 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_freight_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FREIGHTDATA']._serialized_start=59
  _globals['_FREIGHTDATA']._serialized_end=239
# @@protoc_insertion_point(module_scope)
