# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_sign_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_sign_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16stru_sign_status.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"n\n\nSignStatus\x12\x10\n\x08isSigned\x18\x01 \x01(\x08\x12\x12\n\nisRewarded\x18\x02 \x01(\x08\x12\x14\n\x0cisSupplement\x18\x03 \x01(\x08\x12\x10\n\x08signTime\x18\x04 \x01(\x03\x12\x12\n\nrewardTime\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_sign_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNSTATUS']._serialized_start=57
  _globals['_SIGNSTATUS']._serialized_end=167
# @@protoc_insertion_point(module_scope)
