# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_equip_enchant_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_equip_enchant_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_equip_enchant_type_pb2 as enum__e__equip__enchant__type__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_equip_enchant_info.proto\x12\x06zproto\x1a\x1f\x65num_e_equip_enchant_type.proto\x1a\x15stru_dirty_mask.proto\"s\n\x10\x45quipEnchantInfo\x12\x19\n\x11\x65nchantItemTypeId\x18\x01 \x01(\x05\x12\x14\n\x0c\x65nchantLevel\x18\x02 \x01(\x05\x12.\n\x0b\x65nchantType\x18\x03 \x01(\x0e\x32\x19.zproto.EEquipEnchantTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_equip_enchant_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIPENCHANTINFO']._serialized_start=97
  _globals['_EQUIPENCHANTINFO']._serialized_end=212
# @@protoc_insertion_point(module_scope)
