# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_equip_attr_set.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_equip_attr_set.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_equip_attr_set.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"\xd1\x03\n\x0c\x45quipAttrSet\x12\x36\n\tbasicAttr\x18\x01 \x03(\x0b\x32#.zproto.EquipAttrSet.BasicAttrEntry\x12:\n\x0b\x61\x64vanceAttr\x18\x02 \x03(\x0b\x32%.zproto.EquipAttrSet.AdvanceAttrEntry\x12\x38\n\nrecastAttr\x18\x03 \x03(\x0b\x32$.zproto.EquipAttrSet.RecastAttrEntry\x12\x42\n\x0frareQualityAttr\x18\x04 \x03(\x0b\x32).zproto.EquipAttrSet.RareQualityAttrEntry\x1a\x30\n\x0e\x42\x61sicAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10\x41\x64vanceAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0fRecastAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x36\n\x14RareQualityAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_equip_attr_set_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET']._serialized_start=61
  _globals['_EQUIPATTRSET']._serialized_end=526
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._serialized_start=319
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._serialized_end=367
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._serialized_start=369
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._serialized_end=419
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._serialized_start=421
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._serialized_end=470
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._serialized_start=472
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._serialized_end=526
# @@protoc_insertion_point(module_scope)
