# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_equip_attr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_equip_attr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_equip_attr_set_pb2 as stru__equip__attr__set__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_equip_attr.proto\x12\x06zproto\x1a\x19stru_equip_attr_set.proto\x1a\x15stru_dirty_mask.proto\"\xec\x05\n\tEquipAttr\x12\x33\n\tbaseAttrs\x18\x04 \x03(\x0b\x32 .zproto.EquipAttr.BaseAttrsEntry\x12\x17\n\x0fperfectionValue\x18\x07 \x01(\x05\x12\x13\n\x0brecastCount\x18\x08 \x01(\x05\x12\x18\n\x10totalRecastCount\x18\t \x01(\x05\x12\x33\n\tbasicAttr\x18\n \x03(\x0b\x32 .zproto.EquipAttr.BasicAttrEntry\x12\x37\n\x0b\x61\x64vanceAttr\x18\x0b \x03(\x0b\x32\".zproto.EquipAttr.AdvanceAttrEntry\x12\x35\n\nrecastAttr\x18\x0c \x03(\x0b\x32!.zproto.EquipAttr.RecastAttrEntry\x12\x17\n\x0fperfectionLevel\x18\r \x01(\x05\x12?\n\x0frareQualityAttr\x18\x0e \x03(\x0b\x32&.zproto.EquipAttr.RareQualityAttrEntry\x12\x1a\n\x12maxPerfectionValue\x18\x0f \x01(\x05\x12*\n\x0c\x65quipAttrSet\x18\x11 \x01(\x0b\x32\x14.zproto.EquipAttrSet\x12\x18\n\x10\x62reakThroughTime\x18\x12 \x01(\x05\x1a\x30\n\x0e\x42\x61seAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x30\n\x0e\x42\x61sicAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10\x41\x64vanceAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0fRecastAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x36\n\x14RareQualityAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_equip_attr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIPATTR_BASEATTRSENTRY']._loaded_options = None
  _globals['_EQUIPATTR_BASEATTRSENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTR_BASICATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTR_BASICATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTR_ADVANCEATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTR_ADVANCEATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTR_RECASTATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTR_RECASTATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTR_RAREQUALITYATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTR_RAREQUALITYATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTR']._serialized_start=84
  _globals['_EQUIPATTR']._serialized_end=832
  _globals['_EQUIPATTR_BASEATTRSENTRY']._serialized_start=575
  _globals['_EQUIPATTR_BASEATTRSENTRY']._serialized_end=623
  _globals['_EQUIPATTR_BASICATTRENTRY']._serialized_start=625
  _globals['_EQUIPATTR_BASICATTRENTRY']._serialized_end=673
  _globals['_EQUIPATTR_ADVANCEATTRENTRY']._serialized_start=675
  _globals['_EQUIPATTR_ADVANCEATTRENTRY']._serialized_end=725
  _globals['_EQUIPATTR_RECASTATTRENTRY']._serialized_start=727
  _globals['_EQUIPATTR_RECASTATTRENTRY']._serialized_end=776
  _globals['_EQUIPATTR_RAREQUALITYATTRENTRY']._serialized_start=778
  _globals['_EQUIPATTR_RAREQUALITYATTRENTRY']._serialized_end=832
# @@protoc_insertion_point(module_scope)
