# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_life_profession_work.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_life_profession_work.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_life_profession_work_info_pb2 as stru__life__profession__work__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fstru_life_profession_work.proto\x12\x06zproto\x1a$stru_life_profession_work_info.proto\x1a\x15stru_dirty_mask.proto\"\x9b\x01\n\x12LifeProfessionWork\x12>\n\x16lifeProfessionWorkInfo\x18\x01 \x01(\x0b\x32\x1e.zproto.LifeProfessionWorkInfo\x12\x45\n\x1dLifeProfessionWorkHistoryInfo\x18\x02 \x03(\x0b\x32\x1e.zproto.LifeProfessionWorkInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_life_profession_work_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIFEPROFESSIONWORK']._serialized_start=105
  _globals['_LIFEPROFESSIONWORK']._serialized_end=260
# @@protoc_insertion_point(module_scope)
