# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_quest_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_quest_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_quest_step_status_pb2 as enum__e__quest__step__status__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_quest_data.proto\x12\x06zproto\x1a\x1e\x65num_e_quest_step_status.proto\x1a\x15stru_dirty_mask.proto\"\xd2\x03\n\tQuestData\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06stepId\x18\x02 \x01(\r\x12\r\n\x05state\x18\x03 \x01(\r\x12\x33\n\ttargetNum\x18\x04 \x03(\x0b\x32 .zproto.QuestData.TargetNumEntry\x12\x39\n\x0ctargetMaxNum\x18\x05 \x03(\x0b\x32#.zproto.QuestData.TargetMaxNumEntry\x12\x15\n\rstepLimitTime\x18\x06 \x01(\x03\x12,\n\nstepStatus\x18\x07 \x01(\x0e\x32\x18.zproto.EQuestStepStatus\x12\x14\n\x0c\x61\x64\x64LimitTime\x18\x08 \x01(\r\x12\x35\n\ntargetType\x18\t \x03(\x0b\x32!.zproto.QuestData.TargetTypeEntry\x1a\x30\n\x0eTargetNumEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x33\n\x11TargetMaxNumEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0fTargetTypeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_quest_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTDATA_TARGETNUMENTRY']._loaded_options = None
  _globals['_QUESTDATA_TARGETNUMENTRY']._serialized_options = b'8\001'
  _globals['_QUESTDATA_TARGETMAXNUMENTRY']._loaded_options = None
  _globals['_QUESTDATA_TARGETMAXNUMENTRY']._serialized_options = b'8\001'
  _globals['_QUESTDATA_TARGETTYPEENTRY']._loaded_options = None
  _globals['_QUESTDATA_TARGETTYPEENTRY']._serialized_options = b'8\001'
  _globals['_QUESTDATA']._serialized_start=89
  _globals['_QUESTDATA']._serialized_end=555
  _globals['_QUESTDATA_TARGETNUMENTRY']._serialized_start=403
  _globals['_QUESTDATA_TARGETNUMENTRY']._serialized_end=451
  _globals['_QUESTDATA_TARGETMAXNUMENTRY']._serialized_start=453
  _globals['_QUESTDATA_TARGETMAXNUMENTRY']._serialized_end=504
  _globals['_QUESTDATA_TARGETTYPEENTRY']._serialized_start=506
  _globals['_QUESTDATA_TARGETTYPEENTRY']._serialized_end=555
# @@protoc_insertion_point(module_scope)
