# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dance_ball.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dance_ball.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dancer_info_pb2 as stru__dancer__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_dance_ball.proto\x12\x06zproto\x1a\x16stru_dancer_info.proto\x1a\x15stru_dirty_mask.proto\"\xa9\x02\n\tDanceBall\x12\x0f\n\x07\x64\x61nceId\x18\x01 \x01(\x05\x12\x11\n\tbeginTime\x18\x02 \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x03\x12\x11\n\trandIndex\x18\x04 \x01(\x05\x12/\n\x07\x64\x61ncers\x18\x05 \x03(\x0b\x32\x1e.zproto.DanceBall.DancersEntry\x12\x0e\n\x06\x62uffId\x18\x06 \x01(\x05\x12\r\n\x05npcId\x18\x07 \x01(\x05\x12\x13\n\x0bnpcPosIndex\x18\x08 \x01(\x05\x12\x15\n\rsumDanceScore\x18\t \x01(\x05\x12\x14\n\x0chasNotifyNpc\x18\n \x01(\x08\x1a\x42\n\x0c\x44\x61ncersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.zproto.DancerInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dance_ball_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DANCEBALL_DANCERSENTRY']._loaded_options = None
  _globals['_DANCEBALL_DANCERSENTRY']._serialized_options = b'8\001'
  _globals['_DANCEBALL']._serialized_start=81
  _globals['_DANCEBALL']._serialized_end=378
  _globals['_DANCEBALL_DANCERSENTRY']._serialized_start=312
  _globals['_DANCEBALL_DANCERSENTRY']._serialized_end=378
# @@protoc_insertion_point(module_scope)
