# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_award.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_award.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_item_pb2 as stru__item__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_dungeon_award.proto\x12\x06zproto\x1a\x0fstru_item.proto\x1a\x15stru_dirty_mask.proto\"\xb6\x01\n\x0c\x44ungeonAward\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.zproto.DungeonAward.ItemsEntry\x12\x12\n\nflagAssist\x18\x02 \x01(\x05\x12\x12\n\nawardCount\x18\x03 \x01(\x05\x12\x12\n\nfirstItems\x18\x04 \x03(\x03\x1a:\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.zproto.Item:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_award_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONAWARD_ITEMSENTRY']._loaded_options = None
  _globals['_DUNGEONAWARD_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONAWARD']._serialized_start=77
  _globals['_DUNGEONAWARD']._serialized_end=259
  _globals['_DUNGEONAWARD_ITEMSENTRY']._serialized_start=201
  _globals['_DUNGEONAWARD_ITEMSENTRY']._serialized_end=259
# @@protoc_insertion_point(module_scope)
