# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_season_medal_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_season_medal_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_medal_hole_pb2 as stru__medal__hole__pb2
import stru_medal_node_pb2 as stru__medal__node__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_season_medal_info.proto\x12\x06zproto\x1a\x15stru_medal_hole.proto\x1a\x15stru_medal_node.proto\x1a\x15stru_dirty_mask.proto\"\xf6\x02\n\x0fSeasonMedalInfo\x12\x10\n\x08seasonId\x18\x01 \x01(\r\x12\x45\n\x0fnormalHoleInfos\x18\x02 \x03(\x0b\x32,.zproto.SeasonMedalInfo.NormalHoleInfosEntry\x12\'\n\x0c\x63oreHoleInfo\x18\x03 \x01(\x0b\x32\x11.zproto.MedalHole\x12I\n\x11\x63oreHoleNodeInfos\x18\x04 \x03(\x0b\x32..zproto.SeasonMedalInfo.CoreHoleNodeInfosEntry\x1aI\n\x14NormalHoleInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.zproto.MedalHole:\x02\x38\x01\x1aK\n\x16\x43oreHoleNodeInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.zproto.MedalNode:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_season_medal_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEASONMEDALINFO_NORMALHOLEINFOSENTRY']._loaded_options = None
  _globals['_SEASONMEDALINFO_NORMALHOLEINFOSENTRY']._serialized_options = b'8\001'
  _globals['_SEASONMEDALINFO_COREHOLENODEINFOSENTRY']._loaded_options = None
  _globals['_SEASONMEDALINFO_COREHOLENODEINFOSENTRY']._serialized_options = b'8\001'
  _globals['_SEASONMEDALINFO']._serialized_start=110
  _globals['_SEASONMEDALINFO']._serialized_end=484
  _globals['_SEASONMEDALINFO_NORMALHOLEINFOSENTRY']._serialized_start=334
  _globals['_SEASONMEDALINFO_NORMALHOLEINFOSENTRY']._serialized_end=407
  _globals['_SEASONMEDALINFO_COREHOLENODEINFOSENTRY']._serialized_start=409
  _globals['_SEASONMEDALINFO_COREHOLENODEINFOSENTRY']._serialized_end=484
# @@protoc_insertion_point(module_scope)
