# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_item_package.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_item_package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_package_pb2 as stru__package__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_item_package.proto\x12\x06zproto\x1a\x12stru_package.proto\x1a\x15stru_dirty_mask.proto\"\x83\x03\n\x0bItemPackage\x12\x33\n\x08packages\x18\x01 \x03(\x0b\x32!.zproto.ItemPackage.PackagesEntry\x12\x39\n\x0bunlockItems\x18\x02 \x03(\x0b\x32$.zproto.ItemPackage.UnlockItemsEntry\x12\x10\n\x08quickBar\x18\x03 \x01(\x05\x12\x10\n\x08itemUuid\x18\x04 \x01(\x05\x12\x37\n\nuseGroupCd\x18\x05 \x03(\x0b\x32#.zproto.ItemPackage.UseGroupCdEntry\x1a@\n\rPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.zproto.Package:\x02\x38\x01\x1a\x32\n\x10UnlockItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0fUseGroupCdEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_item_package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMPACKAGE_PACKAGESENTRY']._loaded_options = None
  _globals['_ITEMPACKAGE_PACKAGESENTRY']._serialized_options = b'8\001'
  _globals['_ITEMPACKAGE_UNLOCKITEMSENTRY']._loaded_options = None
  _globals['_ITEMPACKAGE_UNLOCKITEMSENTRY']._serialized_options = b'8\001'
  _globals['_ITEMPACKAGE_USEGROUPCDENTRY']._loaded_options = None
  _globals['_ITEMPACKAGE_USEGROUPCDENTRY']._serialized_options = b'8\001'
  _globals['_ITEMPACKAGE']._serialized_start=79
  _globals['_ITEMPACKAGE']._serialized_end=466
  _globals['_ITEMPACKAGE_PACKAGESENTRY']._serialized_start=299
  _globals['_ITEMPACKAGE_PACKAGESENTRY']._serialized_end=363
  _globals['_ITEMPACKAGE_UNLOCKITEMSENTRY']._serialized_start=365
  _globals['_ITEMPACKAGE_UNLOCKITEMSENTRY']._serialized_end=415
  _globals['_ITEMPACKAGE_USEGROUPCDENTRY']._serialized_start=417
  _globals['_ITEMPACKAGE_USEGROUPCDENTRY']._serialized_end=466
# @@protoc_insertion_point(module_scope)
