# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_profession_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_profession_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_profession_info_pb2 as stru__profession__info__pb2
import stru_profession_skill_info_pb2 as stru__profession__skill__info__pb2
import stru_profession_talent_info_pb2 as stru__profession__talent__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astru_profession_list.proto\x12\x06zproto\x1a\x1astru_profession_info.proto\x1a stru_profession_skill_info.proto\x1a!stru_profession_talent_info.proto\x1a\x15stru_dirty_mask.proto\"\xbf\x04\n\x0eProfessionList\x12\x17\n\x0f\x63urProfessionId\x18\x01 \x01(\x05\x12\x1c\n\x14\x63urAssistProfessions\x18\x03 \x03(\x05\x12\x42\n\x0eprofessionList\x18\x04 \x03(\x0b\x32*.zproto.ProfessionList.ProfessionListEntry\x12\x46\n\x10\x61oyiSkillInfoMap\x18\x07 \x03(\x0b\x32,.zproto.ProfessionList.AoyiSkillInfoMapEntry\x12\x19\n\x11totalTalentPoints\x18\x08 \x01(\r\x12\x1d\n\x15totalTalentResetCount\x18\t \x01(\r\x12:\n\ntalentList\x18\n \x03(\x0b\x32&.zproto.ProfessionList.TalentListEntry\x1aM\n\x13ProfessionListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.ProfessionInfo:\x02\x38\x01\x1aT\n\x15\x41oyiSkillInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.zproto.ProfessionSkillInfo:\x02\x38\x01\x1aO\n\x0fTalentListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.zproto.ProfessionTalentInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_profession_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFESSIONLIST_PROFESSIONLISTENTRY']._loaded_options = None
  _globals['_PROFESSIONLIST_PROFESSIONLISTENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONLIST_AOYISKILLINFOMAPENTRY']._loaded_options = None
  _globals['_PROFESSIONLIST_AOYISKILLINFOMAPENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONLIST_TALENTLISTENTRY']._loaded_options = None
  _globals['_PROFESSIONLIST_TALENTLISTENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONLIST']._serialized_start=159
  _globals['_PROFESSIONLIST']._serialized_end=734
  _globals['_PROFESSIONLIST_PROFESSIONLISTENTRY']._serialized_start=490
  _globals['_PROFESSIONLIST_PROFESSIONLISTENTRY']._serialized_end=567
  _globals['_PROFESSIONLIST_AOYISKILLINFOMAPENTRY']._serialized_start=569
  _globals['_PROFESSIONLIST_AOYISKILLINFOMAPENTRY']._serialized_end=653
  _globals['_PROFESSIONLIST_TALENTLISTENTRY']._serialized_start=655
  _globals['_PROFESSIONLIST_TALENTLISTENTRY']._serialized_end=734
# @@protoc_insertion_point(module_scope)
