# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_hero_key_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_hero_key_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_hero_key_item_info_pb2 as stru__hero__key__item__info__pb2
import stru_item_pb2 as stru__item__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stru_dungeon_hero_key_info.proto\x12\x06zproto\x1a\x1dstru_hero_key_item_info.proto\x1a\x0fstru_item.proto\x1a\x15stru_dirty_mask.proto\"\x91\x02\n\x12\x44ungeonHeroKeyInfo\x12\x0e\n\x06\x63harId\x18\x01 \x01(\x03\x12!\n\x0bheroKeyItem\x18\x02 \x03(\x0b\x32\x0c.zproto.Item\x12\x38\n\x07keyInfo\x18\x03 \x03(\x0b\x32\'.zproto.DungeonHeroKeyInfo.KeyInfoEntry\x12\x1d\n\x07useItem\x18\x04 \x01(\x0b\x32\x0c.zproto.Item\x12&\n\x10heroKeyAwardItem\x18\x05 \x03(\x0b\x32\x0c.zproto.Item\x1aG\n\x0cKeyInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.HeroKeyItemInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_hero_key_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONHEROKEYINFO_KEYINFOENTRY']._loaded_options = None
  _globals['_DUNGEONHEROKEYINFO_KEYINFOENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONHEROKEYINFO']._serialized_start=116
  _globals['_DUNGEONHEROKEYINFO']._serialized_end=389
  _globals['_DUNGEONHEROKEYINFO_KEYINFOENTRY']._serialized_start=318
  _globals['_DUNGEONHEROKEYINFO_KEYINFOENTRY']._serialized_end=389
# @@protoc_insertion_point(module_scope)
