# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_profession_skill_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_profession_skill_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stru_profession_skill_info.proto\x12\x06zproto\x1a\x15stru_dirty_mask.proto\"\x80\x02\n\x13ProfessionSkillInfo\x12\x0f\n\x07skillId\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x17\n\x0freplaceSkillIds\x18\x03 \x03(\x05\x12\x14\n\x0cremodelLevel\x18\x04 \x01(\x05\x12\x14\n\x0c\x63urSkillSkin\x18\x05 \x01(\x05\x12K\n\x10\x61\x63tiveSkillSkins\x18\x06 \x03(\x0b\x32\x31.zproto.ProfessionSkillInfo.ActiveSkillSkinsEntry\x1a\x37\n\x15\x41\x63tiveSkillSkinsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_profession_skill_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFESSIONSKILLINFO_ACTIVESKILLSKINSENTRY']._loaded_options = None
  _globals['_PROFESSIONSKILLINFO_ACTIVESKILLSKINSENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONSKILLINFO']._serialized_start=68
  _globals['_PROFESSIONSKILLINFO']._serialized_end=324
  _globals['_PROFESSIONSKILLINFO_ACTIVESKILLSKINSENTRY']._serialized_start=269
  _globals['_PROFESSIONSKILLINFO_ACTIVESKILLSKINSENTRY']._serialized_end=324
# @@protoc_insertion_point(module_scope)
