# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_settlement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_settlement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dungeon_award_pb2 as stru__dungeon__award__pb2
import stru_dungeon_world_boss_settlement_pb2 as stru__dungeon__world__boss__settlement__pb2
import stru_settlement_position_pb2 as stru__settlement__position__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_dungeon_settlement.proto\x12\x06zproto\x1a\x18stru_dungeon_award.proto\x1a(stru_dungeon_world_boss_settlement.proto\x1a\x1estru_settlement_position.proto\x1a\x15stru_dirty_mask.proto\"\x8f\x03\n\x11\x44ungeonSettlement\x12\x10\n\x08passTime\x18\x01 \x01(\x05\x12\x33\n\x05\x61ward\x18\x02 \x03(\x0b\x32$.zproto.DungeonSettlement.AwardEntry\x12\x43\n\rsettlementPos\x18\x03 \x03(\x0b\x32,.zproto.DungeonSettlement.SettlementPosEntry\x12?\n\x13worldBossSettlement\x18\x04 \x01(\x0b\x32\".zproto.DungeonWorldBossSettlement\x12\x17\n\x0fmasterModeScore\x18\x05 \x01(\x05\x1a\x42\n\nAwardEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zproto.DungeonAward:\x02\x38\x01\x1aP\n\x12SettlementPosEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.zproto.SettlementPosition:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_settlement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONSETTLEMENT_AWARDENTRY']._loaded_options = None
  _globals['_DUNGEONSETTLEMENT_AWARDENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONSETTLEMENT_SETTLEMENTPOSENTRY']._loaded_options = None
  _globals['_DUNGEONSETTLEMENT_SETTLEMENTPOSENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONSETTLEMENT']._serialized_start=165
  _globals['_DUNGEONSETTLEMENT']._serialized_end=564
  _globals['_DUNGEONSETTLEMENT_AWARDENTRY']._serialized_start=416
  _globals['_DUNGEONSETTLEMENT_AWARDENTRY']._serialized_end=482
  _globals['_DUNGEONSETTLEMENT_SETTLEMENTPOSENTRY']._serialized_start=484
  _globals['_DUNGEONSETTLEMENT_SETTLEMENTPOSENTRY']._serialized_end=564
# @@protoc_insertion_point(module_scope)
