# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_structure.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_structure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_int_vec3_pb2 as stru__int__vec3__pb2
import stru_structure_farmland_info_pb2 as stru__structure__farmland__info__pb2
import stru_structure_lamplight_info_pb2 as stru__structure__lamplight__info__pb2
import stru_structure_material_info_pb2 as stru__structure__material__info__pb2
import stru_vec4_pb2 as stru__vec4__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stru_structure.proto\x12\x06zproto\x1a\x13stru_int_vec3.proto\x1a\"stru_structure_farmland_info.proto\x1a#stru_structure_lamplight_info.proto\x1a\"stru_structure_material_info.proto\x1a\x0fstru_vec4.proto\"\xea\x02\n\tStructure\x12\x0c\n\x04uuid\x18\x01 \x01(\x03\x12\x12\n\nclientUuid\x18\x02 \x01(\x03\x12\x0f\n\x07groupId\x18\x03 \x01(\x03\x12\x0e\n\x06itemId\x18\x04 \x01(\x05\x12\x0e\n\x06\x63harId\x18\x05 \x01(\x03\x12!\n\x08position\x18\x06 \x01(\x0b\x32\x0f.zproto.IntVec3\x12 \n\nquaternion\x18\x07 \x01(\x0b\x32\x0c.zproto.Vec4\x12\x16\n\x0eoperatorCharId\x18\x08 \x01(\x03\x12\x0c\n\x04name\x18\t \x01(\t\x12\x33\n\x0cmaterialInfo\x18\n \x01(\x0b\x32\x1d.zproto.StructureMaterialInfo\x12\x35\n\rlamplightInfo\x18\x0b \x01(\x0b\x32\x1e.zproto.StructureLamplightInfo\x12\x33\n\x0c\x66\x61rmlandInfo\x18\x0c \x01(\x0b\x32\x1d.zproto.StructureFarmlandInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_structure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRUCTURE']._serialized_start=180
  _globals['_STRUCTURE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
