# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_char_team.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_char_team.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_team_mem_data_pb2 as stru__team__mem__data__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stru_char_team.proto\x12\x06zproto\x1a\x18stru_team_mem_data.proto\x1a\x15stru_dirty_mask.proto\"\x9b\x02\n\x08\x43harTeam\x12\x0e\n\x06teamId\x18\x01 \x01(\x03\x12\x10\n\x08leaderId\x18\x02 \x01(\x03\x12\x14\n\x0cteamTargetId\x18\x03 \x01(\r\x12\x0f\n\x07teamNum\x18\x04 \x01(\r\x12\x0f\n\x07\x63harIds\x18\x05 \x03(\x03\x12\x12\n\nisMatching\x18\x06 \x01(\x08\x12\x17\n\x0f\x63harTeamVersion\x18\x07 \x01(\x05\x12<\n\x0eteamMemberData\x18\x08 \x03(\x0b\x32$.zproto.CharTeam.TeamMemberDataEntry\x1aJ\n\x13TeamMemberDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.zproto.TeamMemData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_char_team_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARTEAM_TEAMMEMBERDATAENTRY']._loaded_options = None
  _globals['_CHARTEAM_TEAMMEMBERDATAENTRY']._serialized_options = b'8\001'
  _globals['_CHARTEAM']._serialized_start=82
  _globals['_CHARTEAM']._serialized_end=365
  _globals['_CHARTEAM_TEAMMEMBERDATAENTRY']._serialized_start=291
  _globals['_CHARTEAM_TEAMMEMBERDATAENTRY']._serialized_end=365
# @@protoc_insertion_point(module_scope)
