# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_union_activity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_union_activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_union_activity_target_pb2 as stru__union__activity__target__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_union_activity.proto\x12\x06zproto\x1a stru_union_activity_target.proto\"\xcd\x02\n\rUnionActivity\x12\x17\n\x0flastRefreshTime\x18\x01 \x01(\x03\x12=\n\x0cunionTargets\x18\x02 \x03(\x0b\x32\'.zproto.UnionActivity.UnionTargetsEntry\x12\x15\n\rnextAwardTime\x18\x03 \x01(\x03\x12\x43\n\x0fnextRefreshTime\x18\x04 \x03(\x0b\x32*.zproto.UnionActivity.NextRefreshTimeEntry\x1aP\n\x11UnionTargetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.zproto.UnionActivityTarget:\x02\x38\x01\x1a\x36\n\x14NextRefreshTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_union_activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNIONACTIVITY_UNIONTARGETSENTRY']._loaded_options = None
  _globals['_UNIONACTIVITY_UNIONTARGETSENTRY']._serialized_options = b'8\001'
  _globals['_UNIONACTIVITY_NEXTREFRESHTIMEENTRY']._loaded_options = None
  _globals['_UNIONACTIVITY_NEXTREFRESHTIMEENTRY']._serialized_options = b'8\001'
  _globals['_UNIONACTIVITY']._serialized_start=72
  _globals['_UNIONACTIVITY']._serialized_end=405
  _globals['_UNIONACTIVITY_UNIONTARGETSENTRY']._serialized_start=269
  _globals['_UNIONACTIVITY_UNIONTARGETSENTRY']._serialized_end=349
  _globals['_UNIONACTIVITY_NEXTREFRESHTIMEENTRY']._serialized_start=351
  _globals['_UNIONACTIVITY_NEXTREFRESHTIMEENTRY']._serialized_end=405
# @@protoc_insertion_point(module_scope)
