# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_login_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_login_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_device_info_pb2 as stru__device__info__pb2
import stru_launch_param_pb2 as stru__launch__param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_login_request.proto\x12\x06zproto\x1a\x16stru_device_info.proto\x1a\x17stru_launch_param.proto\"\xa8\x03\n\x0cLoginRequest\x12\x0e\n\x06openId\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0f\n\x07sdkType\x18\x04 \x01(\x05\x12\x11\n\tchannelId\x18\x05 \x01(\x05\x12\n\n\x02os\x18\x06 \x01(\x05\x12\x14\n\x0cplatformType\x18\x07 \x01(\x05\x12&\n\ndeviceInfo\x18\x08 \x01(\x0b\x32\x12.zproto.DeviceInfo\x12\x15\n\rclientVersion\x18\t \x01(\t\x12\x17\n\x0fprotocolVersion\x18\n \x01(\t\x12\x15\n\rconfigVersion\x18\x0b \x01(\t\x12\x0e\n\x06\x61reaId\x18\x0c \x01(\x05\x12\x19\n\x11iOSAdServiceToken\x18\r \x01(\t\x12\x12\n\npayExtData\x18\x0e \x01(\t\x12\x1d\n\x15\x63lientResourceVersion\x18\x0f \x01(\t\x12(\n\x0blaunchParam\x18\x12 \x01(\x0b\x32\x13.zproto.LaunchParam\x12\x13\n\x0b\x61reaIdToken\x18\x13 \x01(\t\x12\x13\n\x0bisCloudGame\x18\x14 \x01(\x08\x12\x12\n\ndistinctID\x18\x15 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_login_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=86
  _globals['_LOGINREQUEST']._serialized_end=510
# @@protoc_insertion_point(module_scope)
