# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_team_activity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_team_activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_assign_scene_params_pb2 as stru__assign__scene__params__pb2
import enum_e_team_activity_state_pb2 as enum__e__team__activity__state__pb2
import stru_team_activity_dungeon_info_pb2 as stru__team__activity__dungeon__info__pb2
import stru_team_dungeon_key_info_pb2 as stru__team__dungeon__key__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_team_activity.proto\x12\x06zproto\x1a\x1estru_assign_scene_params.proto\x1a enum_e_team_activity_state.proto\x1a%stru_team_activity_dungeon_info.proto\x1a stru_team_dungeon_key_info.proto\"\x96\x03\n\x0cTeamActivity\x12\x12\n\nactivityId\x18\x01 \x01(\r\x12)\n\x05state\x18\x02 \x01(\x0e\x32\x1a.zproto.ETeamActivityState\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x34\n\x0b\x64ungeonInfo\x18\x04 \x01(\x0b\x32\x1f.zproto.TeamActivityDungeonInfo\x12\x10\n\x08\x61greeMem\x18\x05 \x03(\x03\x12\x14\n\x0c\x63heckMembers\x18\x06 \x03(\x03\x12\x10\n\x08refuseId\x18\x07 \x01(\x03\x12\x34\n\x11\x61ssignSceneParams\x18\x08 \x01(\x0b\x32\x19.zproto.AssignSceneParams\x12@\n\x0e\x61wardCountInfo\x18\t \x03(\x0b\x32(.zproto.TeamActivity.AwardCountInfoEntry\x1aQ\n\x13\x41wardCountInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.zproto.TeamDungeonKeyInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_team_activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAMACTIVITY_AWARDCOUNTINFOENTRY']._loaded_options = None
  _globals['_TEAMACTIVITY_AWARDCOUNTINFOENTRY']._serialized_options = b'8\001'
  _globals['_TEAMACTIVITY']._serialized_start=176
  _globals['_TEAMACTIVITY']._serialized_end=582
  _globals['_TEAMACTIVITY_AWARDCOUNTINFOENTRY']._serialized_start=501
  _globals['_TEAMACTIVITY_AWARDCOUNTINFOENTRY']._serialized_end=582
# @@protoc_insertion_point(module_scope)
