# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dungeon_enter_limit_pb2 as stru__dungeon__enter__limit__pb2
import stru_dungeon_info_pb2 as stru__dungeon__info__pb2
import stru_dungeon_week_target_list_pb2 as stru__dungeon__week__target__list__pb2
import stru_raid_record_pb2 as stru__raid__record__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_dungeon_list.proto\x12\x06zproto\x1a\x1estru_dungeon_enter_limit.proto\x1a\x17stru_dungeon_info.proto\x1a#stru_dungeon_week_target_list.proto\x1a\x16stru_raid_record.proto\x1a\x15stru_dirty_mask.proto\"\xda\x03\n\x0b\x44ungeonList\x12\x41\n\x0f\x63ompleteDungeon\x18\x01 \x03(\x0b\x32(.zproto.DungeonList.CompleteDungeonEntry\x12\x11\n\tresetTime\x18\x02 \x01(\r\x12\x1e\n\x16normalDungeonPassCount\x18\x03 \x01(\r\x12\x34\n\x11\x64ungeonEnterLimit\x18\x04 \x01(\x0b\x32\x19.zproto.DungeonEnterLimit\x12\x31\n\nweekTarget\x18\x05 \x01(\x0b\x32\x1d.zproto.DungeonWeekTargetList\x12\x10\n\x08isAssist\x18\x06 \x01(\x08\x12\x41\n\x0fraidRecordTable\x18\x07 \x03(\x0b\x32(.zproto.DungeonList.RaidRecordTableEntry\x1aK\n\x14\x43ompleteDungeonEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.zproto.DungeonInfo:\x02\x38\x01\x1aJ\n\x14RaidRecordTableEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.zproto.RaidRecord:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONLIST_COMPLETEDUNGEONENTRY']._loaded_options = None
  _globals['_DUNGEONLIST_COMPLETEDUNGEONENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONLIST_RAIDRECORDTABLEENTRY']._loaded_options = None
  _globals['_DUNGEONLIST_RAIDRECORDTABLEENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONLIST']._serialized_start=177
  _globals['_DUNGEONLIST']._serialized_end=651
  _globals['_DUNGEONLIST_COMPLETEDUNGEONENTRY']._serialized_start=500
  _globals['_DUNGEONLIST_COMPLETEDUNGEONENTRY']._serialized_end=575
  _globals['_DUNGEONLIST_RAIDRECORDTABLEENTRY']._serialized_start=577
  _globals['_DUNGEONLIST_RAIDRECORDTABLEENTRY']._serialized_end=651
# @@protoc_insertion_point(module_scope)
