# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mark_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mark_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_mark_info_pb2 as stru__mark__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stru_mark_data.proto\x12\x06zproto\x1a\x14stru_mark_info.proto\x1a\x15stru_dirty_mask.proto\"\xa6\x01\n\x08MarkData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x36\n\x0bmarkInfoMap\x18\x02 \x03(\x0b\x32!.zproto.MarkData.MarkInfoMapEntry\x12\x10\n\x08markUuid\x18\x03 \x01(\x05\x1a\x44\n\x10MarkInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.zproto.MarkInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mark_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKDATA_MARKINFOMAPENTRY']._loaded_options = None
  _globals['_MARKDATA_MARKINFOMAPENTRY']._serialized_options = b'8\001'
  _globals['_MARKDATA']._serialized_start=78
  _globals['_MARKDATA']._serialized_end=244
  _globals['_MARKDATA_MARKINFOMAPENTRY']._serialized_start=176
  _globals['_MARKDATA_MARKINFOMAPENTRY']._serialized_end=244
# @@protoc_insertion_point(module_scope)
