# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_basic_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_basic_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_body_size_pb2 as enum__e__body__size__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_basic_data.proto\x12\x06zproto\x1a\x16\x65num_e_body_size.proto\x1a\x15stru_dirty_mask.proto\"\xf5\x02\n\tBasicData\x12\x0e\n\x06\x63harID\x18\x01 \x01(\x03\x12\x0e\n\x06showId\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\x05\x12#\n\x08\x62odySize\x18\x05 \x01(\x0e\x32\x11.zproto.EBodySize\x12\r\n\x05level\x18\x06 \x01(\x05\x12\x0f\n\x07sceneId\x18\x07 \x01(\x05\x12\x15\n\rpersonalState\x18\x08 \x03(\x05\x12\x13\n\x0bofflineTime\x18\t \x01(\x03\x12\x11\n\tsceneGuid\x18\n \x01(\t\x12\x12\n\ncreateTime\x18\x0b \x01(\x03\x12\x17\n\x0f\x63urTalentPoolId\x18\x0c \x01(\r\x12\x0f\n\x07\x62otAiId\x18\r \x01(\r\x12\x17\n\x0fregisterChannel\x18\x0e \x01(\x05\x12\x11\n\tcharState\x18\x0f \x01(\x04\x12\x12\n\nonlineTime\x18\x10 \x01(\x03\x12\x16\n\x0esumSaveDiamond\x18\x11 \x01(\x03\x12\x10\n\x08isNewbie\x18\x12 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_basic_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASICDATA']._serialized_start=81
  _globals['_BASICDATA']._serialized_end=454
# @@protoc_insertion_point(module_scope)
