# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_team_member_social_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_team_member_social_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_avatar_info_pb2 as stru__avatar__info__pb2
import stru_basic_data_pb2 as stru__basic__data__pb2
import stru_equip_data_pb2 as stru__equip__data__pb2
import stru_face_data_pb2 as stru__face__data__pb2
import stru_fashion_data_pb2 as stru__fashion__data__pb2
import stru_personal_zone_show_pb2 as stru__personal__zone__show__pb2
import stru_profession_data_pb2 as stru__profession__data__pb2
import stru_user_attr_data_pb2 as stru__user__attr__data__pb2
import stru_user_scene_info_pb2 as stru__user__scene__info__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"stru_team_member_social_data.proto\x12\x06zproto\x1a\x16stru_avatar_info.proto\x1a\x15stru_basic_data.proto\x1a\x15stru_equip_data.proto\x1a\x14stru_face_data.proto\x1a\x17stru_fashion_data.proto\x1a\x1dstru_personal_zone_show.proto\x1a\x1astru_profession_data.proto\x1a\x19stru_user_attr_data.proto\x1a\x1astru_user_scene_info.proto\x1a\x15stru_dirty_mask.proto\"\x92\x03\n\x14TeamMemberSocialData\x12$\n\tbasicData\x18\x01 \x01(\x0b\x32\x11.zproto.BasicData\x12&\n\navatarInfo\x18\x02 \x01(\x0b\x32\x12.zproto.AvatarInfo\x12\"\n\x08\x66\x61\x63\x65\x44\x61ta\x18\x03 \x01(\x0b\x32\x10.zproto.FaceData\x12.\n\x0eprofessionData\x18\x04 \x01(\x0b\x32\x16.zproto.ProfessionData\x12$\n\tequipData\x18\x05 \x01(\x0b\x32\x11.zproto.EquipData\x12(\n\x0b\x66\x61shionData\x18\x06 \x01(\x0b\x32\x13.zproto.FashionData\x12,\n\ruserSceneInfo\x18\x07 \x01(\x0b\x32\x15.zproto.UserSceneInfo\x12*\n\x0cuserAttrData\x18\x08 \x01(\x0b\x32\x14.zproto.UserAttrData\x12.\n\x0cpersonalZone\x18\t \x01(\x0b\x32\x18.zproto.PersonalZoneShowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_team_member_social_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAMMEMBERSOCIALDATA']._serialized_start=301
  _globals['_TEAMMEMBERSOCIALDATA']._serialized_end=703
# @@protoc_insertion_point(module_scope)
