# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_gasha_record.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_gasha_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_gasha_record_item_info_pb2 as stru__gasha__record__item__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_gasha_record.proto\x12\x06zproto\x1a!stru_gasha_record_item_info.proto\"\x7f\n\x0bGashaRecord\x12\x12\n\ncharIdPool\x18\x01 \x01(\t\x12\x0e\n\x06poolId\x18\x02 \x01(\r\x12\x34\n\x0fgashaRecordInfo\x18\x03 \x03(\x0b\x32\x1b.zproto.GashaRecordItemInfo\x12\x16\n\x0e\x66irstTimestamp\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_gasha_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GASHARECORD']._serialized_start=70
  _globals['_GASHARECORD']._serialized_end=197
# @@protoc_insertion_point(module_scope)
