# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_temp_photo_cache_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_temp_photo_cache_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stru_temp_photo_cache_info.proto\x12\x06zproto\"\xd0\x01\n\x12tempPhotoCacheInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttempPhoto\x18\x02 \x01(\t\x12\x14\n\x0ctempOriPhoto\x18\x03 \x01(\t\x12\x16\n\x0etempThumbPhoto\x18\x04 \x01(\t\x12\x10\n\x08shotTime\x18\x05 \x01(\x04\x12\x13\n\x0bshotTimeStr\x18\x06 \x01(\t\x12\x11\n\tshotPlace\x18\x07 \x01(\t\x12\x14\n\x0c\x64\x65\x63orateData\x18\x08 \x01(\t\x12\x0e\n\x06height\x18\t \x01(\r\x12\r\n\x05width\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_temp_photo_cache_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPPHOTOCACHEINFO']._serialized_start=45
  _globals['_TEMPPHOTOCACHEINFO']._serialized_end=253
# @@protoc_insertion_point(module_scope)
