# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_match_param_context.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_match_param_context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_match_mode_pb2 as enum__e__match__mode__pb2
import enum_e_match_strategy_pb2 as enum__e__match__strategy__pb2
import stru_match_key_info_pb2 as stru__match__key__info__pb2
import stru_match_player_info_pb2 as stru__match__player__info__pb2
import any_pb2 as any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estru_match_param_context.proto\x12\x06zproto\x1a\x17\x65num_e_match_mode.proto\x1a\x1b\x65num_e_match_strategy.proto\x1a\x19stru_match_key_info.proto\x1a\x1cstru_match_player_info.proto\x1a\tany.proto\"\xc7\x02\n\x11MatchParamContext\x12%\n\tmatchMode\x18\x01 \x01(\x0e\x32\x12.zproto.EMatchMode\x12\x12\n\nmatchToken\x18\x04 \x01(\t\x12\x0e\n\x06teamId\x18\x05 \x01(\x03\x12-\n\rmatchStrategy\x18\x06 \x01(\x0e\x32\x16.zproto.EMatchStrategy\x12\x30\n\x12matchStrategyParam\x18\x07 \x01(\x0b\x32\x14.google.protobuf.Any\x12*\n\x0cmatchKeyInfo\x18\x08 \x01(\x0b\x32\x14.zproto.MatchKeyInfo\x12\x15\n\rmatchGrainKey\x18\t \x01(\t\x12\x30\n\x0fmatchPlayerInfo\x18\n \x01(\x0b\x32\x17.zproto.MatchPlayerInfo\x12\x11\n\tdungeonId\x18\x0b \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_match_param_context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHPARAMCONTEXT']._serialized_start=165
  _globals['_MATCHPARAMCONTEXT']._serialized_end=492
# @@protoc_insertion_point(module_scope)
