# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_tss_account_info_proto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_tss_account_info_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!stru_tss_account_info_proto.proto\x12\x06zproto\"\xe7\x01\n\x13TssAccountInfoProto\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63ountType\x18\x02 \x01(\r\x12\x0e\n\x06platId\x18\x03 \x01(\r\x12\x0e\n\x06gameId\x18\x04 \x01(\r\x12\x0f\n\x07worldId\x18\x05 \x01(\r\x12\x11\n\tchannelId\x18\x06 \x01(\r\x12\x0e\n\x06roleId\x18\x07 \x01(\x03\x12\x10\n\x08\x61ntiData\x18\x08 \x01(\x0c\x12\x11\n\taccountId\x18\t \x01(\t\x12\x10\n\x08\x63lientIp\x18\n \x01(\t\x12\x10\n\x08roleName\x18\x0b \x01(\t\x12\r\n\x05index\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_tss_account_info_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TSSACCOUNTINFOPROTO']._serialized_start=46
  _globals['_TSSACCOUNTINFOPROTO']._serialized_end=277
# @@protoc_insertion_point(module_scope)
