# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_privilege_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_privilege_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_launch_platform_pb2 as enum__launch__platform__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_privilege_data.proto\x12\x06zproto\x1a\x1a\x65num_launch_platform.proto\x1a\x15stru_dirty_mask.proto\"l\n\rPrivilegeData\x12.\n\x0elaunchPlatform\x18\x01 \x01(\x0e\x32\x16.zproto.LaunchPlatform\x12\x13\n\x0bisPrivilege\x18\x02 \x01(\x08\x12\x16\n\x0elastUpdateTime\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_privilege_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIVILEGEDATA']._serialized_start=88
  _globals['_PRIVILEGEDATA']._serialized_end=196
# @@protoc_insertion_point(module_scope)
