# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_team_mem_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_team_mem_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_team_member_social_data_pb2 as stru__team__member__social__data__pb2
import stru_dirty_mask_pb2 as stru__dirty__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_team_mem_data.proto\x12\x06zproto\x1a\"stru_team_member_social_data.proto\x1a\x15stru_dirty_mask.proto\"\xd5\x01\n\x0bTeamMemData\x12\x0e\n\x06\x63harId\x18\x01 \x01(\x03\x12\x11\n\tenterTime\x18\x02 \x01(\r\x12\x12\n\ncallStatus\x18\x03 \x01(\x05\x12\x10\n\x08talentId\x18\x04 \x01(\x05\x12\x14\n\x0conlineStatus\x18\x05 \x01(\x05\x12\x0f\n\x07sceneId\x18\x06 \x01(\x05\x12\x13\n\x0bvoiceIsOpen\x18\x07 \x01(\x08\x12\x0f\n\x07groupId\x18\x08 \x01(\x05\x12\x30\n\nsocialData\x18\t \x01(\x0b\x32\x1c.zproto.TeamMemberSocialDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_team_mem_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAMMEMDATA']._serialized_start=96
  _globals['_TEAMMEMDATA']._serialized_end=309
# @@protoc_insertion_point(module_scope)
