# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: table_config_option.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'table_config_option.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import descriptor_pb2 as descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19table_config_option.proto\x12\x0ctable_config\x1a\x10\x64\x65scriptor.proto\"2\n\x0cMessageTable\x12\x10\n\x08msg_type\x18\x01 \x01(\t\x12\x10\n\x08pbs_path\x18\x02 \x03(\t\")\n\x0cSecondaryKey\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\"u\n\x16TableConfigFieldOption\x12\x13\n\x0bprimary_key\x18\x01 \x01(\x08\x12\x12\n\nnon_unique\x18\x02 \x01(\x08\x12\x32\n\x0esecondary_keys\x18\x03 \x03(\x0b\x32\x1a.table_config.SecondaryKey:P\n\tmsg_table\x12\x1f.google.protobuf.MessageOptions\x18\xf0\xa2\x04 \x01(\x0b\x32\x1a.table_config.MessageTable:[\n\x0c\x66ield_option\x12\x1d.google.protobuf.FieldOptions\x18\xd4\xa3\x04 \x01(\x0b\x32$.table_config.TableConfigFieldOptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'table_config_option_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETABLE']._serialized_start=61
  _globals['_MESSAGETABLE']._serialized_end=111
  _globals['_SECONDARYKEY']._serialized_start=113
  _globals['_SECONDARYKEY']._serialized_end=154
  _globals['_TABLECONFIGFIELDOPTION']._serialized_start=156
  _globals['_TABLECONFIGFIELDOPTION']._serialized_end=273
# @@protoc_insertion_point(module_scope)
