# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TargetTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TargetTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11TargetTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xfa\x02\n\x0fTargetTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x13\n\nTargetType\x18\xe0\x05 \x01(\x05\x12\x0c\n\x03Num\x18\xb3\x07 \x01(\x05\x12\x10\n\x07SceneId\x18\xe2\x0b \x01(\x05\x12\x1a\n\x05Param\x18\xb7\t \x01(\x0b\x32\n.int_array\x12\x12\n\tTargetPos\x18\xde\x08 \x01(\t\x12\x14\n\x0bIsTeamShare\x18\x85\x0f \x01(\x08\x12\x1d\n\tTargetDes\x18\xff\t \x01(\x0b\x32\t.mlstring\x12\x16\n\x0eIsShowProgress\x18\x38 \x01(\x08\x12$\n\nSpVariable\x18\x98\x02 \x01(\x0b\x32\x0f.mlstring_array\x12)\n\x0fSpVariableLimit\x18\xbb\x02 \x01(\x0b\x32\x0f.mlstring_array\x12(\n\x0eSpVariableName\x18\xd6\x0f \x01(\x0b\x32\x0f.mlstring_array\x12-\n\x18IsShowSpVariableProgress\x18\xa0\x06 \x01(\x0b\x32\n.int_array\"\x89\x01\n\x0eTargetTableMgr\x12\x30\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32!.bokura.TargetTableMgr.DatasEntry\x1a\x45\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.bokura.TargetTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TargetTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGETTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_TARGETTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_TARGETTABLEBASE']._serialized_start=49
  _globals['_TARGETTABLEBASE']._serialized_end=427
  _globals['_TARGETTABLEMGR']._serialized_start=430
  _globals['_TARGETTABLEMGR']._serialized_end=567
  _globals['_TARGETTABLEMGR_DATASENTRY']._serialized_start=498
  _globals['_TARGETTABLEMGR_DATASENTRY']._serialized_end=567
# @@protoc_insertion_point(module_scope)
