# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TempAttrTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TempAttrTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13TempAttrTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xc6\x01\n\x11TempAttrTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x03\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12\r\n\x04\x44\x65sc\x18\xa1\x0f \x01(\t\x12\x11\n\x08\x41ttrType\x18\xf9\x04 \x01(\x05\x12\x12\n\tLogicType\x18\xc6\x01 \x01(\x05\x12\x1e\n\nAttrParams\x18\n \x01(\x0b\x32\n.int_array\x12\x13\n\nLowerLimit\x18\xbb\n \x01(\x05\x12\x13\n\nUpperLimit\x18\xcf\x0c \x01(\x05\x12\x15\n\x0cIsSyncClient\x18\xf0\x06 \x01(\x08\"\x8f\x01\n\x10TempAttrTableMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.TempAttrTableMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.TempAttrTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TempAttrTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPATTRTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_TEMPATTRTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_TEMPATTRTABLEBASE']._serialized_start=51
  _globals['_TEMPATTRTABLEBASE']._serialized_end=249
  _globals['_TEMPATTRTABLEMGR']._serialized_start=252
  _globals['_TEMPATTRTABLEMGR']._serialized_end=395
  _globals['_TEMPATTRTABLEMGR_DATASENTRY']._serialized_start=324
  _globals['_TEMPATTRTABLEMGR_DATASENTRY']._serialized_end=395
# @@protoc_insertion_point(module_scope)
