# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TrapTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TrapTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fTrapTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xd4\x01\n\rTrapTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\r\n\x04Name\x18\xb7\x03 \x01(\t\x12\x10\n\x07SkillId\x18\xbf\x08 \x01(\x05\x12\x1c\n\x07\x42uffIds\x18\xfc\x0e \x01(\x0b\x32\n.int_array\x12\x15\n\x0cTriggerRange\x18\xe8\x02 \x01(\x02\x12\x14\n\x0b\x41ttributeId\x18\xa1\x0e \x01(\x05\x12\x10\n\x07ModelId\x18\xab\x04 \x01(\x05\x12\x1d\n\x08LifeInfo\x18\x9c\x03 \x01(\x0b\x32\n.int_array\x12\x19\n\x04Tags\x18\xe8\x01 \x01(\x0b\x32\n.int_array\"\x83\x01\n\x0cTrapTableMgr\x12.\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x1f.bokura.TrapTableMgr.DatasEntry\x1a\x43\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.bokura.TrapTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TrapTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAPTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_TRAPTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_TRAPTABLEBASE']._serialized_start=47
  _globals['_TRAPTABLEBASE']._serialized_end=259
  _globals['_TRAPTABLEMGR']._serialized_start=262
  _globals['_TRAPTABLEMGR']._serialized_end=393
  _globals['_TRAPTABLEMGR_DATASENTRY']._serialized_start=326
  _globals['_TRAPTABLEMGR_DATASENTRY']._serialized_end=393
# @@protoc_insertion_point(module_scope)
