# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WeaponSkinTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'WeaponSkinTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15WeaponSkinTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe0\x01\n\x13WeaponSkinTableBase\x12\x0b\n\x02Id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04Name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\r\n\x04Icon\x18\x81\t \x01(\t\x12\x19\n\x05Intro\x18\xe4\x05 \x01(\x0b\x32\t.mlstring\x12\"\n\rWeaponModelId\x18\xad\x01 \x01(\x0b\x32\n.int_array\x12\x11\n\x08WeaponId\x18\xb8\x07 \x01(\x05\x12\x11\n\x08Original\x18\x8a\x04 \x01(\x05\x12\x0f\n\x06Unlock\x18\x82\r \x01(\x05\x12\x1d\n\tUnlockDes\x18\xc7\x0f \x01(\x0b\x32\t.mlstring\"\x95\x01\n\x12WeaponSkinTableMgr\x12\x34\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32%.bokura.WeaponSkinTableMgr.DatasEntry\x1aI\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.bokura.WeaponSkinTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeaponSkinTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEAPONSKINTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_WEAPONSKINTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_WEAPONSKINTABLEBASE']._serialized_start=53
  _globals['_WEAPONSKINTABLEBASE']._serialized_end=277
  _globals['_WEAPONSKINTABLEMGR']._serialized_start=280
  _globals['_WEAPONSKINTABLEMGR']._serialized_end=429
  _globals['_WEAPONSKINTABLEMGR_DATASENTRY']._serialized_start=356
  _globals['_WEAPONSKINTABLEMGR_DATASENTRY']._serialized_end=429
# @@protoc_insertion_point(module_scope)
